### PR TITLE
fix cmd injection

### PR DESCRIPTION
**Pull request by zhentaocc**
## Description
Fix command injection during model conversion:
Details:
the system passes user-supplied input directly to exec(), eval(), and os.system() methods without validation, which could result in command injection.

### 1. Why the change?

Fix command injection during model conversion

### 2. User API changes

N/A

### 3. Summary of the change 

use `subprocess.checkoutput` instead of `os.system`.

### 4. How to test?
- [ ] Unit test

### CODE REVIEW

**Review by TheaperDeng — APPROVED** [review]
LGTM

**Comment by TheaperDeng** [comment]
just found this PR......, we definitely need to merge this. @zhentaocc do you have any changes need to do on this PR? I will merge it tomorrow.

**Comment by TheaperDeng** [comment]
@hjzin any comments about this PR? I will merge it today if you are ok with it.

**Comment by hjzin** [comment]
> @hjzin any comments about this PR? I will merge it today if you are ok with it.

nothing to update, you can merge it.

**Pull request merged**
