### PR TITLE
add integration test , update core submodule to latest

### PR DESCRIPTION
**Pull request by luchy0120**

### CODE REVIEW

**Comment by yiheng** [comment]
can you merge the commit?

**Comment by luchy0120** [comment]
ok , merged them

**Comment by yiheng** [comment]
Will the integration test be run by default or user need input an flag to trigger it?

**Comment by luchy0120** [comment]
it will be running on jenkins and command is something like:
robot test.robot  , it's not integrated with maven

**Comment by yiheng** [comment]
LGTM

**Pull request merged**
