### PR TITLE
LLM Inference Docker on Linux

### PR DESCRIPTION
**Pull request by Uxito-Ada**
### 4. How to test?
- [ ] N/A
- [ ] Unit test
- [ ] Application test
- [ ] Document test
- [ ] ...

### 5. New dependencies

- [ ] New Python dependencies
       - Dependency1 
       - Dependency2
       - ...
- [ ] New Java/Scala dependencies and their license
       - Dependency1 and license1
       - Dependency2 and license2
       - ...

### CODE REVIEW

**Review by glorysdj — COMMENTED** [review]
Need remove all fastchat/llm-demo serving related dependencies.
this image is only for bigdl-llm inference.

**Comment by jason-dai** [comment]
See https://github.com/intel-analytics/BigDL/issues/8950

**Comment by azhuvath** [comment]
> Need remove all fastchat/llm-demo serving related dependencies. this image is only for bigdl-llm inference.

Is this Dockerfile for GPU or CPU? I can see many SGX references in it which we are not planning to use.

**Comment by Uxito-Ada** [comment]
This PR is closed as we will add a GPU version which is coming in the other PR.

**Pull request closed without merging**
