### PR TITLE
[Enhancement ] - Add set label and get uri api

### PR DESCRIPTION
**Pull request by wzhongyuan**
## What changes were proposed in this pull request?

Add set label and get uri api

## How was this patch tested?

unit test

## Related links or issues (optional)
fixed https://github.com/intel-analytics/BigDL/issues/2468

### CODE REVIEW

**Comment by jenniew** [comment]
I think this API: def setLabel(labelMap: mutable.Map[String, Float], imageFeature: ImageFeature) is better to put into ImageFeature. As it is an operation to image feature.

**Comment by wzhongyuan** [comment]
@jenniew  makes sense. just updated it.

**Comment by wzhongyuan** [comment]
@jenniew   Added example as well, please review and let me know if you have any quesiton

**Comment by wzhongyuan** [comment]
PR validation passed http://172.168.2.101:8080/job/BigDL-PR-Validation-v3/480/

**Comment by jenniew** [comment]
After fix the issues in documents, you can merge.

**Comment by wzhongyuan** [comment]
thanks, updated the doc typo issue.   
I am now  running with another PR Job and will merge once it passes

**Comment by wzhongyuan** [comment]
PR validation passed http://172.168.2.101:8080/job/BigDL-PR-Validation-v3/483/
Merging it

**Pull request merged**
