### PR TITLE
Add AutoXGBoost API Guide

### PR DESCRIPTION
**Pull request by liangs6212**

### CODE REVIEW

**Comment by liangs6212** [comment]
issue link: #3337

**Comment by liangs6212** [comment]
https://smalldl.readthedocs.io/en/auto-xgb-api/doc/PythonAPI/AutoML/automl.html#autoxgboost

**Comment by yushan111** [comment]
Add example code snips

**Comment by liangs6212** [comment]
https://smalldl.readthedocs.io/en/auto-xgb-api/doc/PythonAPI/AutoML/automl.html

**Comment by yushan111** [comment]
```
Automatic hyperparameter optimization for XGBoost models.
AutoXGBoost is inherited from AutoEstimator. You could refer to AutoEstimator API Guide for more APIs.
```
Change the description according to the comment before.

**Comment by yushan111** [comment]
LGTM

**Pull request merged**
