### PR TITLE
Fix script on yarn

### PR DESCRIPTION
**Pull request by hkvision**
## What changes were proposed in this pull request?

1. Running the following command on yarn will fail to import any BigDL module:
```
${BIGDL_HOME}/bin/pyspark-with-bigdl.sh --master yarn 
```
Discussed with @jenniew need to export `PYTHONPATH` so that both the driver and executor can find the python zip for bigdl.

2. Fix doc specify dependency of `six` #2239 

3. Fix typo of `jupyter` in the script name.

## How was this patch tested?

Manual test on yarn.

## Related links or issues (optional)
fixed https://github.com/intel-analytics/BigDL/issues/XXX

### CODE REVIEW

**Comment by yiheng** [comment]
LGTM

**Comment by zhichao-li** [comment]
is it a must for standalone mode as well? seems like this script works smoothly for standalone cluster for a long time.

**Comment by hkvision** [comment]
@zhichao-li I manually tested on standalone mode and it is not needed. The origin script works for standalone but not for yarn.

**Comment by jenniew** [comment]
LGTM

**Comment by hkvision** [comment]
jenkins passed http://172.168.2.101:8080/job/BigDL-PR-Validation-v3/386/

**Comment by jason-dai** [comment]
We also need add some integration tests to automatically test it.

**Comment by hkvision** [comment]
@jason-dai I've opened an issue to keep track of this: https://github.com/intel-analytics/BigDL/issues/2390

**Pull request merged**
