### PR TITLE
Friesian serving recommender http server

### PR DESCRIPTION
**Pull request by cyita**
## Description

Add friesian serving recommender http server & test code & decouple recommender implementation from recommender grpc server code.

### 1. Why the change?

According to XueTang's requirement.

### 2. User API changes

Add friesian serving recommender http api, for example,
```bash
# get recommender metrics
http://localhost:8080/recommender/metrics

# get feature,  recall and ranking metrics
http://localhost:8080/recommender/clientMetrics

# reset metrics
http://localhost:8080/recommender/resetMetrics

# get recommend ids
http://localhost:8080/recommender/recommend/{id}?canK={candidate_num}&k={recommend_num}
default candidate_num: 50
default recommend_num: 10
example:
http://localhost:8080/recommender/recommend/15                                 # id=15, canK=50, k=10
http://localhost:8080/recommender/recommend/15?canK=100               # id=15, canK=100, k=10
http://localhost:8080/recommender/recommend/15?k=20                       # id=15, canK=50, k=20
http://localhost:8080/recommender/recommend/15?canK=100&k=20    # id=15, canK=100, k=20
```

### 3. Summary of the change 

Add a Jersey Grizzly2 HTTP server.

### 4. How to test?
- [x] Manual test
- [x] Jenkins

### 5. New dependencies

- [ ] New Java/Scala dependencies and their license
       - org.glassfish.jersey.containers:jersey-container-grizzly2-http:2.36 / SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0
       - org.glassfish.jersey.inject:jersey-hk2:2.36 / SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0

### CODE REVIEW

**Comment by cyita** [comment]
TODO:
- [ ] new docker image test

**Comment by cyita** [comment]
Jenkins passed http://10.112.231.51:18888/view/BigDL-2.0-PR/job/BigDL-Friesian-PR-Validation/166/

**Comment by jason-dai** [comment]
@glorysdj please take a look at the new dependency

@cyita do we need to include these dependency in our jar?

**Comment by cyita** [comment]
> @glorysdj please take a look at the new dependency
> 
> @cyita do we need to include these dependency in our jar?

Maybe we can provide the jersey jars in the docker image instead of compiling them into the serving jar, but it will be error-prone since we/the user should deal with the dependency conflicts like the spark in our docker image.

**Comment by jason-dai** [comment]
> > @glorysdj please take a look at the new dependency
> > @cyita do we need to include these dependency in our jar?
> 
> Maybe we can provide the jersey jars in the docker image instead of compiling them into the serving jar, but it will be error-prone since we/the user should deal with the dependency conflicts like the spark in our docker image.

If the docker image contains everything, why would the user need to deal with the dependency?

**Comment by cyita** [comment]
> > > @glorysdj please take a look at the new dependency
> > > @cyita do we need to include these dependency in our jar?
> > 
> > 
> > Maybe we can provide the jersey jars in the docker image instead of compiling them into the serving jar, but it will be error-prone since we/the user should deal with the dependency conflicts like the spark in our docker image.
> 
> If the docker image contains everything, why would the user need to deal with the dependency?

The user may want to run the serving jar directly if they do some code modification?

**Comment by cyita** [comment]
Will remove the jersey jars in the serving jar and add them to the docker image.

**Comment by cyita** [comment]
Jenkins passed http://10.112.231.51:18888/view/BigDL-2.0-PR/job/BigDL-Friesian-PR-Validation/178/

**Pull request merged**
