### PR TITLE
Fix the conflict of `KMP_AFFINITY` and onnxruntime 

### PR DESCRIPTION
**Pull request by MeouSker77**
## Description

The default value of `KMP_AFFINITY` has some conflict with onnxruntime, change the default value from `granularity=fine,compact,1,0` to `granularity=fine,1,0` to avoid the conflict

### CODE REVIEW

**Comment by MeouSker77** [comment]
APRT

**Comment by glorysdj** [comment]
@MeouSker77 Your benchmark <https://github.com/intel-analytics/BigDL/pull/5764#issuecomment-1247459879> has finished,             see <https://github.com/intel-analytics/BigDL/actions/runs/3057155440> for details

Use `uuid=e68e5508-3496-11ed-9161-ea16527ea10a` to query the result

**Comment by rnwang04** [comment]
when I use `granularity=fine,1,0` for inference
it will be many warning:
image
then I change to `granularity=fine`

**Comment by MeouSker77** [comment]
> when I use `granularity=fine,1,0` for inference
> it will be many warning:

maybe I should remove the `1,0` option, too

**Comment by MeouSker77** [comment]
APRT

**Comment by glorysdj** [comment]
@MeouSker77 Your benchmark <https://github.com/intel-analytics/BigDL/pull/5764#issuecomment-1247472429> has finished,             see <https://github.com/intel-analytics/BigDL/actions/runs/3057243092> for details

Use `uuid=a10166ca-349a-11ed-933e-ea16527ea10a` to query the result

**Comment by MeouSker77** [comment]
It seems changing `KMP_AFFINITY` has no effect on the performance

**Comment by TheaperDeng** [comment]
> It seems changing `KMP_AFFINITY` has no effect on the performance

that does not surprise me...

**Comment by TheaperDeng** [comment]
hopefully this will save `bigdl.chronos.autots` as well

**Pull request merged**
