### PR TITLE
Chronos: Update Windows User Guide

### PR DESCRIPTION
**Pull request by hjzin**
### 1. Why the change?

Now Chronos can run on native Windows, we need to update the Windows User Guide as well.
### 2. User API changes

N/A
### 3. Summary of the change 

- Add Windows User Guide
preview doc: https://zhaojie-doc.readthedocs.io/en/win-user-guide/doc/Chronos/Howto/windows_guide.html

- Add Chronos install page
preview doc: https://zhaojie-doc.readthedocs.io/en/win-user-guide/doc/Chronos/Overview/install.html

- Make prophet available for windows and add prophet related issue in the known issue, because the issue doesn't occur in some situation based on my test.

- Update Chronos install panel
preview doc: https://zhaojie-doc.readthedocs.io/en/win-user-guide/doc/Chronos/Overview/install.html

### 4. How to test?
- [ ] Document test

### CODE REVIEW

**Comment by TheaperDeng** [comment]
This might be a challenging request :)

Please update the installation panel in https://zhaojie-doc.readthedocs.io/en/win-user-guide/doc/Chronos/Overview/install.html as well, to make sure "Please refer to [windows_guide.](https://bigdl.readthedocs.io/en/latest/doc/Chronos/Howto/windows_guide.html)" is shown only when users selected those functionalities that we can not support on native windows (e.g. prophet and distributed). For other cases, the ordinary `pip install ...` should be prompt. 

This may involves some change in https://github.com/intel-analytics/BigDL/blob/main/docs/readthedocs/source/_static/js/chronos_installation_guide.js

**Comment by hjzin** [comment]
> This might be a challenging request :)
> 
> Please update the installation panel in https://zhaojie-doc.readthedocs.io/en/win-user-guide/doc/Chronos/Overview/install.html as well, to make sure "Please refer to [windows_guide.](https://bigdl.readthedocs.io/en/latest/doc/Chronos/Howto/windows_guide.html)" is shown only when users selected those functionalities that we can not support on native windows (e.g. prophet and distributed). For other cases, the ordinary `pip install ...` should be prompt.
> 
> This may involves some change in https://github.com/intel-analytics/BigDL/blob/main/docs/readthedocs/source/_static/js/chronos_installation_guide.js

Good idea, I will work on it.

**Comment by hjzin** [comment]
install panel preview: https://zhaojie-doc.readthedocs.io/en/win-user-guide/doc/Chronos/Overview/install.html

**Comment by TheaperDeng** [comment]
> install panel preview: https://zhaojie-doc.readthedocs.io/en/win-user-guide/doc/Chronos/Overview/install.html

it seems that when users choose "stable(2.1.0)", windows is still supported as the installation panel. We can't support it in 2.1.0 stable release right?

**Comment by TheaperDeng** [comment]
For "Known Issues on Native Windows" could we have a meaningful name to replace "issue1/2/3"?

**Comment by TheaperDeng** [comment]
For the python style check, it should be fixed if you rebase on main.

**Comment by hjzin** [comment]
> > install panel preview: https://zhaojie-doc.readthedocs.io/en/win-user-guide/doc/Chronos/Overview/install.html
> 
> it seems that when users choose "stable(2.1.0)", windows is still supported as the installation panel. We can't support it in 2.1.0 stable release right?

Yeah, good catch.
Fixed the install panel.

**Comment by hjzin** [comment]
> For "Known Issues on Native Windows" could we have a meaningful name to replace "issue1/2/3"?

Added a title for each known issue.
https://zhaojie-doc.readthedocs.io/en/win-user-guide/doc/Chronos/Howto/windows_guide.html

**Pull request merged**
