### PR TITLE
New LR Schedule: add new learning rate decay policy: natural exp

### PR DESCRIPTION
**Pull request by whatbeg**
## What changes were proposed in this pull request?

added new learning rate decay policy: natural exp
updated in 2017. 6. 10. 16:34

## How was this patch tested?

Unit Test Failed since I didn't defined updateHyperParameter(config: Table, state: Table)

### CODE REVIEW

**Comment by yiheng** [comment]
@zhangxiaoli73 Please take a look at it.

**Comment by zhangxiaoli73** [comment]
@whatbeg there is some change for LearningRateSchedule  trait in our new code,  updateHyperParameter(config: Table, state: Table) function has been deprecated, you should implement updateHyperParameter(optimMethod: SGD) function. Please refer to Poly policy as example.

**Comment by whatbeg** [comment]
@zhangxiaoli73 updated. If you think it's not necessary, you can let it go and don't merge it until it's necessary. : )

**Comment by zhangxiaoli73** [comment]
Have anyone used this policy? Code LGTM

**Comment by zhangxiaoli73** [comment]
@whatbeg I think you don't have to override updateHyperParameter(config: Table, state: Table), just  implement updateHyperParameter(optimMethod: SGD) should be ok.

**Comment by whatbeg** [comment]
@zhangxiaoli73 actually updateHyperParameter(config: Table, state: Table) must be define otherwise Unit Test will be failed, since there are method updateHyperParameter(config: Table, state: Table) in trait LearningRateSchedule.

**Comment by zhangxiaoli73** [comment]
@whatbeg Please pull the new code, then you don't have to  define updateHyperParameter(config: Table, state: Table)

**Comment by zhangxiaoli73** [comment]
jenkins pass

**Pull request merged**
