### PR TITLE
Python api support

### PR DESCRIPTION
**Pull request by megaSpoon**
## What changes were proposed in this pull request?

unittest for dl_classifier

## How was this patch tested?

locally set SPARK_HOME to spark-1.5x and run python tests script which is passed successfully.

### CODE REVIEW

**Comment by megaSpoon** [comment]
solution explanation:
dataframe 1.5 in spark-1.5x does not support accessing column by its name so we access it by index number.

**Comment by megaSpoon** [comment]
I will rebase it after review approval.

**Comment by zhichao-li** [comment]
LGTM. Let's merge this once the Jenkins passed, and trigger nightlybuilt(http://172.168.2.101:8080/view/NightlyBuild/job/BigDL-Nightly-Build/) to test against Spark1.5.
@glorysdj should we add Spark1.5 verification back to Jenkins PR validation?

**Comment by megaSpoon** [comment]
@zhichao-li Did I rebase the branch correctly？ There are many commits from others after I rebased mine.

**Comment by megaSpoon** [comment]
I'll reset the commits in my local repo and push to the remote.

**Comment by yiheng** [comment]
Don't use rebase. Use cherry-pick

**Comment by megaSpoon** [comment]
I reforked the repo and sent a new PR #1774

**Pull request closed without merging**
