### PR TITLE
change Table to Tensor in L1HingeEmbeddingCriterion

### PR DESCRIPTION
**Pull request by zhangxiaoli73**
## What changes were proposed in this pull request?

fix issue https://github.com/intel-analytics/BigDL/issues/1058
change Table to Tensor in L1HingeEmbeddingCriterion

### CODE REVIEW

**Comment by zhichao-li** [comment]
LGTM

**Comment by zhichao-li** [comment]
Maybe we should not restrict the target to be a scalar, but I guess we can address that in the other PR.

**Comment by zhichao-li** [comment]
cc @yiheng

**Comment by zhangxiaoli73** [comment]
jekins pass

**Pull request merged**
