### PR TITLE
Support vnni check

### PR DESCRIPTION
**Pull request by MeouSker77**
## Description

Add avx_vnni and avx512_vnni checker

## Usage

```python
from bigdl.llm.utils.isa_checker import check_avx_vnni
from bigdl.llm.utils.isa_checker import check_avx512_vnni

if check_avx_vnni():
    ...

if check_avx512_vnni():
    ...
```

### CODE REVIEW

**Comment by MeouSker77** [comment]
I test it on i9 windows (support avx_vnni but doesn't support avx512_vnni), clx (support avx512_vnni but doesn't support avx_vnni) and spr (support both avx_vnni and avx512_vnni), all works correctly

**Comment by MeouSker77** [comment]
According to 
image
<https://www.felixcloutier.com/x86/cpuid>

we can check avx-vnni by setting eax to 7, ecx to 1, then use cpuid instruction, if returned eax's bit4 is 1, it means avx-vnni is supported

**Comment by jason-dai** [comment]
Can we also check avx (that is, avx1)?

**Comment by MeouSker77** [comment]
> Can we also check avx (that is, avx1)?

added it

**Comment by jason-dai** [comment]
LGTM

**Review by rnwang04 — APPROVED** [review]
LGTM

**Pull request merged**
