### PR TITLE
Qwen2 fp16 sdp

### PR DESCRIPTION
**Pull request by qiuxin2012**
## Description

Qwen2 fp16 sdp

### CODE REVIEW

**Review by rnwang04 — APPROVED** [review]

**Comment by qiuxin2012** [comment]
qwen2 using flash attention on pvc return bad result:
Like:
```
-------------------- Prompt --------------------
AI是什么？
-------------------- Output --------------------
摧残
```
and
```
The truth was stranger than he could have ever imagined, and it led him on a journey that would take him deep into the大半夜, I'll be back
雨中
雨伞
根据以上内容，用自己的语言<|im_end|>
```
Remove use_flash_attention first.

**Comment by jason-dai** [comment]
> qwen2 using flash attention on pvc return bad result: Like:
> 
> ```
> -------------------- Prompt --------------------
> AI是什么？
> -------------------- Output --------------------
> 摧残
> ```
> 
> and
> 
> ```
> The truth was stranger than he could have ever imagined, and it led him on a journey that would take him deep into the大半夜, I'll be back
> 雨中
> 雨伞
> 根据以上内容，用自己的语言<|im_end|>
> ```
> 
> Remove use_flash_attention first.

How about Qwen?

**Comment by qiuxin2012** [comment]
> > qwen2 using flash attention on pvc return bad result: Like:
> > ```
> > -------------------- Prompt --------------------
> > AI是什么？
> > -------------------- Output --------------------
> > 摧残
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and
> > ```
> > The truth was stranger than he could have ever imagined, and it led him on a journey that would take him deep into the大半夜, I'll be back
> > 雨中
> > 雨伞
> > 根据以上内容，用自己的语言<|im_end|>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Remove use_flash_attention first.
> 
> How about Qwen?

Qwen is the good
```
-------------------- Prompt --------------------
AI是什么？
-------------------- Output --------------------
人工智能（AI）是指利用计算机科学和数学来模拟人类智能的技术。它是一种技术，可以使计算机系统像人一样思考、学习、分析和
```

**Comment by qiuxin2012** [comment]
> qwen2 using flash attention on pvc return bad result: Like:
> 
> ```
> -------------------- Prompt --------------------
> AI是什么？
> -------------------- Output --------------------
> 摧残
> ```
> 
> and
> 
> ```
> The truth was stranger than he could have ever imagined, and it led him on a journey that would take him deep into the大半夜, I'll be back
> 雨中
> 雨伞
> 根据以上内容，用自己的语言<|im_end|>
> ```
> 
> Remove use_flash_attention first.

https://github.com/intel-analytics/BigDL/pull/10435 will add this back, we need to reshape the attention output before reshape them.

**Pull request merged**
