### PR TITLE
Fix Mixtral typo

### PR DESCRIPTION
**Pull request by hkvision**

### CODE REVIEW

**Comment by jason-dai** [comment]
Also need to fix https://github.com/intel-analytics/BigDL/blob/main/docs/readthedocs/source/index.rst

**Review by jason-dai — APPROVED** [review]
LGTM

**Comment by rnwang04** [comment]
There is still a `l` missing. Mixtra-8x7B -> Mixtral-8x7B

**Comment by hkvision** [comment]
> There is still a `l` missing. Mixtra-8x7B -> Mixtral-8x7B

oops, will modify in a new PR...

**Pull request merged**
