### PR TITLE
Nano: fix action oom and regression test

### PR DESCRIPTION
**Pull request by MeouSker77**
## Description

Fix acton OOM and regression test

### CODE REVIEW

**Comment by MeouSker77** [comment]
APRT

**Comment by glorysdj** [comment]
@MeouSker77 Your benchmark <https://github.com/intel-analytics/BigDL/pull/6764#issuecomment-1326993962> of workload `tsdataset_processing`             has finished, see <https://github.com/intel-analytics/BigDL/actions/runs/3545159762> for details

Use `uuid='f57629d2-6c73-11ed-9e6c-86d8f8900f97'` to query the result

**Comment by glorysdj** [comment]
@MeouSker77 Your benchmark <https://github.com/intel-analytics/BigDL/pull/6764#issuecomment-1326993962> of workload `forecaster_training`             has finished, see <https://github.com/intel-analytics/BigDL/actions/runs/3545159762> for details

Use `uuid='2a142c34-6c74-11ed-81c8-86d8f8900f97'` to query the result

**Comment by glorysdj** [comment]
@MeouSker77 Your benchmark <https://github.com/intel-analytics/BigDL/pull/6764#issuecomment-1326993962> of workload `forecaster_inference`             has finished, see <https://github.com/intel-analytics/BigDL/actions/runs/3545159762> for details

Use `uuid='82423a72-6c74-11ed-b093-86d8f8900f97'` to query the result

**Comment by glorysdj** [comment]
@MeouSker77 Your benchmark <https://github.com/intel-analytics/BigDL/pull/6764#issuecomment-1326993962> of workload `resnet_inference`             has finished, see <https://github.com/intel-analytics/BigDL/actions/runs/3545159762> for details

It seems there are some errors

**Pull request merged**
