### PR TITLE
add dataformat support

### PR DESCRIPTION
**Pull request by wzhongyuan**
## What changes were proposed in this pull request?

Added input img format data type support : NCHW & NHWC

## How was this patch tested?

Unit test

### CODE REVIEW

**Comment by wzhongyuan** [comment]
@yiheng  I found new data type added to support NHWC & NCHW,  modified the proto file and added related test cases, please help review, thx

**Comment by yiheng** [comment]
LGTM

**Comment by yiheng** [comment]
@yangw1234 can you take a look at this?

**Comment by yangw1234** [comment]
LGTM

**Comment by wzhongyuan** [comment]
PR validation passed, thus merging it into master

http://10.239.47.211:18888/job/BigDL-PR-Validation/1603/

**Pull request merged**
