### PR TITLE
[llm] Initial support of package and quantize

### PR DESCRIPTION
**Pull request by rnwang04**
## Description

To support quantization and further inference, at first, we need involve theses dynamic library and executable file (libllama.so / quantize) into our llm package.
In this PR, try to obtain dynamic library and executable file of three cpp repos(llama.cpp / bloomz.cpp / redpajama.cpp) by skbuild + submodule on Linux.
Also support uniform quantization python API for llama.cpp / bloomz.cpp / redpajama.cpp.

### 1. Why the change?

To obtain dynamic library and executable file of three cpp repos, and provide an uniform  quantization API

### 2. User API changes

Basic usage of quantization is supported.
```python
from bigdl.llm.ggml import quantize

quantize(input_path="./merged_gpt4all_llama_7b/ggml-model-f16.bin",
         output_path="./merged_gpt4all_llama_7b/ggml-model-q4_0.bin",
         model_family="llama",
         dtype="q4_0")
```

### 3. Summary of the change 

- obtain dynamic library and executable file of three cpp repos(llama.cpp / bloomz.cpp / redpajama.cpp) by skbuild + submodule on Linux, finish related CMakeLists.txt  [**only for Linux now**]
```bash
/disk8/miniconda3/envs/test/lib/python3.9/site-packages/bigdl_llm-2.4.0.dev0-py3.9-linux-x86_64.egg/bigdl/llm$ ls bin
quantize-bloomz  quantize-gptneox  quantize-llama
/disk8/miniconda3/envs/test/lib/python3.9/site-packages/bigdl_llm-2.4.0.dev0-py3.9-linux-x86_64.egg/bigdl/llm$ ls lib
libbloom.so  libgptneox.so  libllama.so
```
- provide an uniform quantization API

### 4. How to test?
- [x] Unit test

### CODE REVIEW

**Comment by jason-dai** [comment]
1) Need to support windows first

2) Change API to:
```python
from bigdl.llm import convert_model
convert_model(input="...", output="...", model_family="...", type="INT4")
```

3) Where can the user get the original model (e.g., "ggml-model-f16.bin")?

**Comment by TheaperDeng** [comment]
> 1. Need to support windows first
> 2. Change API to:
> 
> ```python
> from bigdl.llm import convert_model
> convert_model(input="...", output="...", model_family="...", type="INT4")
> ```
> 
> 3. Where can the user get the original model (e.g., "ggml-model-f16.bin")?

3. Another PR is prepared by @plusbang for converting to ggml f16

**Comment by jason-dai** [comment]
> 3. Another PR is prepared by @plusbang for converting to ggml f16

Why do we need that? The expected workflow is that the user will download the standard PyTorch model (e.g., from HuggingFace) and then call `convert_model` to convert it to INT4 model.

**Comment by TheaperDeng** [comment]
> > 3. Another PR is prepared by @plusbang for converting to ggml f16
> 
> Why do we need that? The expected workflow is that the user will download the standard PyTorch model (e.g., from HuggingFace) and then call `convert_model` to convert it to INT4 model.

yeah, we call it convert and quantize for now (as internal function) but actually users will only see 1 method exposed called `convert_model`(or sth else) to help them do both steps.

Currently tasks are divided so some internal part will be pushed as PR once it's ready

**Review by TheaperDeng — APPROVED** [review]
LGTM, we will have win support next PR. as we talked we may have another setup-win.py to make future development easier.

**Comment by rnwang04** [comment]
> 1. Need to support windows first
> 2. Change API to:
> 
> ```python
> from bigdl.llm import convert_model
> convert_model(input="...", output="...", model_family="...", type="INT4")
> ```

Will support Windows in next PR.
maybe change the internal quantize API to below as there are several types INT4 model ?
```python
from bigdl.llm.ggml import quantize
quantize(input="...", output="...", model_family="...", type="q4_0")
```
After convert function is merged, we will expose this API(`from bigdl.llm import convert_model`)

**Comment by jason-dai** [comment]
> Will support Windows in next PR. maybe change the internal quantize API to below as there are several types INT4 model ?

Internally yes

**Pull request merged**
