### PR TITLE
delete logger variable  in LocalPredictor

### LINKED ISSUE #2578: LocalPredictor can not be serialized because of field logger

### PR DESCRIPTION
**Pull request by qiuxin2012**
## What changes were proposed in this pull request?

delete logger variable in LocalPredictor

## How was this patch tested?

unit tests

## Related links or issues (optional)
fixed #2578

### CODE REVIEW

**Comment by yiheng** [comment]
why remove the logger? I don't think this is the right way to fix the issue

**Comment by qiuxin2012** [comment]
The right way to use logger is new a logger in the Object, and import the logger in the corresponding Class.
So making the logger a member of the Class is not a good idea. @yiheng

**Comment by yiheng** [comment]
Yes, you should move the logger into the object.

**Comment by qiuxin2012** [comment]
jenkins passed

**Pull request merged**
