### PR TITLE
AutoXGBoost input Spark DataFrame without collecting to driver

### PR DESCRIPTION
**Pull request by yushan111**
Related issue: #3823

Implementation: Spark `DataFrame` -> `SparkXShards` ->`RayXShards`

UT passed, will test with large data on local and on cluster.

### CODE REVIEW

**Comment by yushan111** [comment]
http://10.112.231.51:18888/view/BigDL-2.0-PR/job/BigDL-Orca-PR-Validation/295/

**Comment by jason-dai** [comment]
LGTM

**Comment by jenniew** [comment]
Can we provide AutoXGBoost example of input of Spark Dataframe?

**Comment by yushan111** [comment]
> Can we provide AutoXGBoost example of input of Spark Dataframe?

Sure. The task has been added in issue #3823

**Pull request merged**
