### PR TITLE
Integration Test related

### PR DESCRIPTION
**Pull request by lopelopelope**
Provide convenience for integration test

### CODE REVIEW

**Comment by yiheng** [comment]
LGTM

**Comment by yiheng** [comment]
PR validation pass?

**Comment by lopelopelope** [comment]
Still running, I will contact you when done @yiheng

**Comment by lopelopelope** [comment]
@i8run I have changed the Quantization.scala as you required

**Comment by lopelopelope** [comment]
@yiheng jenkins passed

**Comment by i8run** [comment]
LGTM

**Pull request merged**
