### PR TITLE
[Enhancement] ImageFrame adding more APIs

### PR DESCRIPTION
**Pull request by wzhongyuan**
## What changes were proposed in this pull request?

Add imageframe based module evaluation and related python API
 
## How was this patch tested?

Model validation with inception v1

## Related links or issues (optional)
fixed https://github.com/intel-analytics/BigDL/issues/2384

### CODE REVIEW

**Comment by wzhongyuan** [comment]
@jenniew  please help review, thanks

**Comment by wzhongyuan** [comment]
I already tested it by running model validation example using Python API

**Comment by jenniew** [comment]
Please add test case of write_parquet.

**Comment by wzhongyuan** [comment]
@jenniew  added. also found a bug in `read_parquet`, we should passed in a spark context instead of sql context, because there is no java version sql context, we should initialize sql context on inside in `PythonBigDL`

**Comment by wzhongyuan** [comment]
PR validation passed http://172.168.2.101:8080/job/BigDL-PR-Validation-v3/475/

**Comment by jenniew** [comment]
I found this issue too.  There is another way, for the py2java method, if isinstance(obj, SQLContext): obj = obj._ssql_ctx to get scala sql context.

**Comment by wzhongyuan** [comment]
@jenniew  ok, but  i don't want to change the common method ,  changing this method only is preferable

**Comment by jenniew** [comment]
OK

**Comment by wzhongyuan** [comment]
Any other concerns？

**Pull request merged**
