### PR TITLE
Table class should not publish internal mutable state to the outside world

### PR DESCRIPTION
**Pull request by yangw1234**
## What changes were proposed in this pull request?

The `Table` class has a `getState()` which used to return the internal mutable state to caller. It is a little dangerous to do that since the `state` could be modified somewhere else, which make it hard for Table to ensure its own invariants. 

This pr fixes this issue by 
1. add `foreach` and `keySet` methods for the caller to get easy readonly access to the elements of the internal `state`
2. modify `getState()` to return a defensive copy of the original state

## How was this patch tested?

existing tests

### CODE REVIEW

**Comment by yiheng** [comment]
LGTM

**Comment by jason-dai** [comment]
Shall we just remove getState()? Or make it private?

**Comment by yangw1234** [comment]
@jason-dai I thought of removing getState() at first, but I was not sure whether we were allowed to change a API like this, so I modify it to return a defensive copy. If it is OK to remove it, I'd love to do that.

**Comment by yiheng** [comment]
I think we can remove it.

**Comment by yangw1234** [comment]
I removed the getState() method

**Comment by yiheng** [comment]
jenkins test job pass. Merge the PR. @yangw1234 thanks for your contribution.

**Pull request merged**
