### PR TITLE
Python regularizer

### PR DESCRIPTION
**Pull request by 122689305**
## What changes were proposed in this pull request?

Transform Regularizer from scala into python

## Related links or issues (optional)
fixed https://github.com/intel-analytics/BigDL/issues/953

### CODE REVIEW

**Comment by 122689305** [comment]
Pass the local test ./run-all.sh
@psyyz10 please take a look

**Comment by zhichao-li** [comment]
@122689305 style check fail.

**Comment by yiheng** [comment]
Just remind another PR https://github.com/intel-analytics/BigDL/pull/975 touched the regularizer interface. @psyyz10 @zhichao-li @plrectco @122689305

**Comment by zhichao-li** [comment]
Jenkins passed.  Merge this first and then @SeaOfOcean can add the `set` method in https://github.com/intel-analytics/BigDL/pull/1048

**Pull request merged**
