### PR TITLE
Fix pickler initialization issue in executor side

### PR DESCRIPTION
**Pull request by wzhongyuan**
## What changes were proposed in this pull request?

Fix pickler initialization issue in executor side

## How was this patch tested?

unit test and manual test

### CODE REVIEW

**Comment by zhichao-li** [comment]
Paste the manual testing script in the description since we cann't reproduce it in unitest?

**Comment by wzhongyuan** [comment]
PR validation passed 
 http://172.168.2.101:8080/job/BigDL-PR-Validation-v3/364/

**Comment by wzhongyuan** [comment]
Also tested manually without any issue

**Comment by wzhongyuan** [comment]
```below script was ran successfully
from bigdl.util.common import *

from bigdl.transform.vision.image import *

from pyspark import SparkContext

from bigdl.nn.layer import *


conf = SparkConf().setMaster("local").setAppName("My App")
sc = SparkContext(conf = conf)
image_frame = ImageFrame.read('hdfs://172.168.2.181:9000/test_img/', sc)

count=image_frame.get_image().count()
print(count)
```

**Pull request merged**
