### PR TITLE
Add more datatypes in convert DataFrame to numpy

### PR DESCRIPTION
**Pull request by hkvision**
Currently many datatypes are not correctly converted, and may cause error in subsequent model forward.

### CODE REVIEW

**Comment by hkvision** [comment]
failed http://10.112.231.51:18888/job/BigDL-Orca-PR-Validation/590/

**Review by yushan111 — APPROVED** [review]
LGTM

**Comment by hkvision** [comment]
In our unit tests, many of the code looks like this:
```
df = rdd.map(lambda x: (np.random.randn(50).astype(np.float).tolist(),
                                [int(np.random.randint(0, 2, size=()))])
                     ).toDF(["feature", "label"])
```
Since python only have float (default is float64), int (default is int64), when converting to DataFrame, the schema will be array<double> and array<bigint>. Then in this case the model will throw error `RuntimeError: expected scalar type Float but found Double`

A few unit tests for example `test.bigdl.orca.learn.ray.pytorch.test_estimator_pytorch_backend.TestPyTorchEstimator testMethod=test_data_parallel_sgd_correctness` throws the opposite error `RuntimeError: expected scalar type Double but found Float`, which is really weird, probably a bug of error report in PyTorch...

@yushan111 Any comments on this?

**Comment by hkvision** [comment]
Comment out the data conversion for array<float> and jenkins passed: http://10.112.231.51:18888/job/BigDL-Orca-PR-Validation/599/

**Pull request closed without merging**
