### PR TITLE
[nano] tf.keras.model usage issue fix 

### PR DESCRIPTION
**Pull request by Django-Jiang**
Solve issue #4748

### CODE REVIEW

**Comment by yangw1234** [comment]
@zhentaocc would you mind helping verify that this pr works for your problem?

**Comment by zhentaocc** [comment]
> @zhentaocc would you mind helping verify that this pr works for your problem?

LGTM. I think added ut is enough to check.

**Comment by yangw1234** [comment]
I think we may also check in the unit tests by calling different methods in the constructed model:
1. regular keras APIs (fit, evaluate, predict, ...)
2. Nano APIs, (fit with multiple processes)

**Comment by yangw1234** [comment]
LGTM

**Comment by TheaperDeng** [comment]
@yangw1234 @Django-Jiang Please test chronos pr validation (i.e. run nano jenkins pr validation in future) This pr breaks chronos pr and nb tests.

**Pull request merged**
