### PR TITLE
enable auto release

### PR DESCRIPTION
**Pull request by lopelopelope**
Enable jenkins do auto release job

### CODE REVIEW

**Comment by lopelopelope** [comment]
@yiheng @zhichao-li

**Comment by zhichao-li** [comment]
Something we can add to enhance the release logic:
1) Check if the generated version match the release version before execute the uploading command: `BigDL-0.3.0rc2-py2.py3-none-manylinux1_x86_64.whl`
2) Delete the generated folder including:"dist" and "build"  before execute `${wheel_command}`

**Comment by lopelopelope** [comment]
@zhichao-li  Already added.

**Comment by zhichao-li** [comment]
LGTM

**Pull request merged**
