### PR TITLE
fix concat when the dimension concatenated along is larger than 2

### LINKED ISSUE #1229: Concat does not work when the dimension concatenated along is larger than 2
The following code will throw an exception 
```scala
    val model = Concat[Float](3)
    model.add(Identity[Float]())
    model.add(Identity[Float]())
    val input = Tensor[Float](2, 2, 2)
    val output = model.forward(input)
```
output
```
requirement failed
java.lang.IllegalArgumentException: requirement failed
	at scala.Predef$.require(Predef.scala:212)
	at com.intel.analytics.bigdl.nn.Concat$$anonfun$updateOutput$1.apply$mcV$sp(Concat.scala:91)
	at com.intel.analytics.bigdl.nn.Concat$$anonfun$updateOutput$1.apply(Concat.scala:79)
	at com.intel.analytics.bigdl.nn.Concat$$anonfun$updateOutput$1.apply(Concat.scala:79)
	at com.intel.analytics.bigdl.utils.ThreadPool$$anonfun$invoke$2.apply(ThreadPool.scala:162)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
```

### PR DESCRIPTION
**Pull request by yangw1234**
## What changes were proposed in this pull request?

fix concat when the dimension concatenated along is larger than 2

## How was this patch tested?

add unit tests

## Related links or issues (optional)
fixed #1229

### CODE REVIEW

**Comment by qiuxin2012** [comment]
Doesn't need so many changes.
Just change 
```
if (target.isContiguous()) {
          // Copy directly when target is Contiguous
          target.copy(currentOutput)
        }
``` 
to
```
if (target.isContiguous() || dimension > 2) {
          // Copy directly when target is Contiguous, and dimension > 2.
          target.copy(currentOutput)
        } 
```

**Comment by yangw1234** [comment]
@qiuxin2012 I thought this would be bad for performance when target tensor is not contiguous. But it turns out (through micro-benchmarks) my change does not make much of a difference. Changing it back.

**Comment by qiuxin2012** [comment]
Please also change the comments.

**Comment by yangw1234** [comment]
pr validation pass

**Pull request merged**
