### PR TITLE
add a performance param to bigdl-nano-init

### PR DESCRIPTION
**Pull request by qiuxin2012**
### 1. Why the change?

add a performance param to bigdl-nano-init

### 2. User API changes

none

### 3. Summary of the change 

```
source bigdl-nano-init performance
```
Can provide another experiment env.

### 4. How to test?
- [ ] N/A
- [ ] Unit test
- [ ] Application test
- [ ] Document test
- [ ] ...

### CODE REVIEW

**Comment by jason-dai** [comment]
> ### 3. Summary of the change
> ```
> source bigdl-nano-init performance
> ```

`source bigdl-nano-init -perf`? @TheaperDeng @yangw1234

**Comment by TheaperDeng** [comment]
> > ### 3. Summary of the change
> > ```
> > source bigdl-nano-init performance
> > ```
> 
> `source bigdl-nano-init -perf`? @TheaperDeng @yangw1234

well I prefer call it `source bigdl-nano-init -extreme`, but `-perf` is kind of easier to users than `performance`

**Comment by qiuxin2012** [comment]
changed to `-p` or `--perf`

**Comment by jason-dai** [comment]
I think we can merge this PR first, and use the new option to run more performance testing?

**Pull request merged**
