### PR TITLE
LLM: Add python 3.10 llm UT

### PR DESCRIPTION
**Pull request by lalalapotter**
## Description

This PR is to add python 3.10 llm-unit-tests and llm binary build.

### CODE REVIEW

**Comment by Oscilloscope98** [comment]
Could we just add a matrix here https://github.com/intel-analytics/BigDL/pull/9302/files#diff-1b45c5f2b467d47315e2c4c04df43baf10d59393a4ab009b8d33321a77ae89ffL49 to enable py310 unit test?

**Comment by lalalapotter** [comment]
> Could we just add a matrix here https://github.com/intel-analytics/BigDL/pull/9302/files#diff-1b45c5f2b467d47315e2c4c04df43baf10d59393a4ab009b8d33321a77ae89ffL49 to enable py310 unit test?

Sure, updated.

**Review by MeouSker77 — APPROVED** [review]
LGTM

**Comment by Oscilloscope98** [comment]
Should we also add the py310 test for arc? https://github.com/intel-analytics/BigDL/pull/9302/files#diff-1b45c5f2b467d47315e2c4c04df43baf10d59393a4ab009b8d33321a77ae89ffR205

**Comment by lalalapotter** [comment]
> Should we also add the py310 test for arc? https://github.com/intel-analytics/BigDL/pull/9302/files#diff-1b45c5f2b467d47315e2c4c04df43baf10d59393a4ab009b8d33321a77ae89ffR205

In this PR we will not include the UT for arc, and arc related UT will be added in other PRs by @Jasonzzt

**Review by Oscilloscope98 — APPROVED** [review]
LGTM

**Pull request merged**
