### PR TITLE
Chronos:  Make `TSDataset` more friendly

### PR DESCRIPTION
**Pull request by liangs6212**
## Description

Before that, since the horizon is not 0, the length of the predicted data will be less than the actual demand data.
Now if `is_predict` set to True, then horizon will be set to 0, which avoids the prediction data being split.

### Usage
```python

test = TSDataset.from_pandas(...)
test.is_predict = True
yhat = forecaster.predict(test)
```

### CODE REVIEW

**Comment by TheaperDeng** [comment]
Should we use a setter for this member? since we want to use it as a external API

**Comment by liangs6212** [comment]
> Should we use a setter for this member? since we want to use it as a external API

Like this?
```python
yhat = forecaster.predict(test, is_predict=True)
```

It looks a little weird, but it's friendly to use.

**Comment by TheaperDeng** [comment]
> > Should we use a setter for this member? since we want to use it as a external API
> 
> Like this?
> 
> ```python
> yhat = forecaster.predict(test, is_predict=True)
> ```
> 
> It looks a little weird, but it's friendly to use.

no I mean make this member a https://docs.python.org/3/library/functions.html#property .

We may try some thing new in this PR, since we might have such syntax supported more and more in future.

**Comment by liangs6212** [comment]
Diff:
 1. Removed redundant parameters(is_predict)
 2. Some changes based on property(experiment)
 3. Descriptor applied(experiment)

**Pull request closed without merging**
