### PR TITLE
Chronos: Update Chronos install guide form's js and css file.

### PR DESCRIPTION
**Pull request by AndyLuo1029**
## Description

Update Chronos install guide form's js and css file to get a better look and more user-friendly functionality.

### CODE REVIEW

**Comment by TheaperDeng** [comment]
Good job, could you provide a demo readthedoc link here?

**Comment by AndyLuo1029** [comment]
I only added disabled function when you click the 'docker' button to show the effect.

**Comment by TheaperDeng** [comment]
Some comments:
1. There seems to be a setting issue in the navigation bar
image
2. disable other options when users choose windows, and guide users to https://bigdl.readthedocs.io/en/latest/doc/Chronos/Overview/windows_guide.html in "Install CMD"
3. guide users to https://bigdl.readthedocs.io/en/latest/doc/Chronos/Overview/chronos.html#tensorflow-backend in "Install CMD" when tensorflow is chosen.
4. guide users to https://github.com/intel-analytics/BigDL/tree/main/docker/chronos-nightly in "install CMD" when docker is chosen.

**Comment by AndyLuo1029** [comment]
Please check the latest version of doc via https://andytestdoc.readthedocs.io/en/latest/doc/Chronos/Overview/chronos.html. The requirements are all met.

**Comment by TheaperDeng** [comment]
just some quick comments, ignore it if it too much effort. we may make the disabled items' background darker to have a better vis experience. Furthermore, could we have a larger fontsize?

others LGTM

**Comment by AndyLuo1029** [comment]
Updated changes above.

**Review by TheaperDeng — APPROVED** [review]
LGTM

**Comment by shane-huang** [comment]
image


In above, change `pmdarima` to `ARIMA`

**Comment by shane-huang** [comment]
The install option is not intuitive enough. For example, for a new user who wants to use chronos for times series forecasting, which option should I use? The new user does not have pytorch or tf

**Comment by TheaperDeng** [comment]
table design will be updated next PR and this PR

**Pull request merged**
