### PR TITLE
Remove final for AbstractModule

### PR DESCRIPTION
**Pull request by Le-Zheng**
remove final for cloneModule( ) and save( )
To fix https://github.com/intel-analytics/BigDL/issues/3000

### CODE REVIEW

**Comment by Le-Zheng** [comment]
PR validation http://10.239.47.210:18080/job/BigDL-PRVN-lite/1132/

**Comment by jason-dai** [comment]
Do we need to remove final for both `cloneModule` and `save`, or `save` only?

**Comment by Le-Zheng** [comment]
Shall we remove all the `final` better? That will avoid override restrictions in the future.

**Comment by jason-dai** [comment]
LGTM

**Comment by jason-dai** [comment]
> Shall we remove all the `final` better? That will avoid override restrictions in the future.

I don't think you should remove all `final`

**Comment by Le-Zheng** [comment]
> > Shall we remove all the `final` better? That will avoid override restrictions in the future.
> 
> I don't think you should remove all `final`

Ok. Currently, we only need to remove `final` for `save( ) `  to support TFTrainingHelper checkpoint.  Update.

**Comment by Le-Zheng** [comment]
Tests passed on Jenkins http://10.239.47.210:18080/job/BigDL-PRVN-lite/1135/

**Pull request merged**
