### PR TITLE
Chronos: Change TCNForecaster's default parameter num_channels to [16]*3

### PR DESCRIPTION
**Pull request by devWangBin**
## Description

Chronos: Change TCNForecaster's default parameter of num_channels from [30]*7  to [16]*3

### 1. Why the change?
Based on experimental results on real datasets, we find that the parameter setting of [16]*3 generally have more stable and superior performance. 

Github issue link: https://github.com/intel-analytics/BigDL/issues/5606

### CODE REVIEW

**Comment by TheaperDeng** [comment]
I am pretty sure this should work, but we should be careful about this. @liangs6212 do you have any comments about this?

**Comment by liangs6212** [comment]
> I am pretty sure this should work, but we should be careful about this. @liangs6212 do you have any comments about this?

Can the same modification be used for TF2 `TCNForecaster`?

**Comment by TheaperDeng** [comment]
> > I am pretty sure this should work, but we should be careful about this. @liangs6212 do you have any comments about this?
> 
> Can the same modification be used for TF2 `TCNForecaster`?

Yeah, good catch. @devWangBin Please change `bigdl.chronos.forecaster.tf.tcnforecaster` as well

**Comment by devWangBin** [comment]
> Yeah, good catch. @devWangBin Please change `bigdl.chronos.forecaster.tf.tcnforecaster` as well
Okay, no problem.

**Review by TheaperDeng — APPROVED** [review]
LGTM

**Comment by TheaperDeng** [comment]
@plusbang @ruobing-wang Since this default value is used everywhere so I am asking more stockholders to have a review

**Comment by rnwang04** [comment]
LGTM

**Comment by plusbang** [comment]
LGTM

**Pull request merged**
