### PR TITLE
Support table for sample-label

### PR DESCRIPTION
**Pull request by hkvision**
## What changes were proposed in this pull request?

Support List of JTensors for label python

## How was this patch tested?

Jenkins.

## Related links or issues (optional)
#1857

### CODE REVIEW

**Comment by hkvision** [comment]
Locally tested with a dummy criterion that takes a table as input/target.

**Comment by jason-dai** [comment]
Please add the dummy criterion as a unit test.

**Comment by hkvision** [comment]
@jason-dai Seems that I have found `MarginRankingCriterion` in BigDL that takes a table of tensors as input. I will use it as the dummy criterion instead and add a unit test.

**Comment by hkvision** [comment]
jenkins passed http://172.168.2.101:8080/job/BigDL-PR-V/372/

**Comment by hkvision** [comment]
@jason-dai @shane-huang have a review?

**Comment by hkvision** [comment]
jenkins passed http://172.168.2.101:8080/view/PR-V/job/BigDL-PR-V/381/

**Comment by yiheng** [comment]
This breaks bigdl-tutorial code. Please take a look at:

http://172.168.2.101:8080/job/BigDL-Nightly-Build-ToturialTests/122/console

**Comment by hkvision** [comment]
Nightly build tutorials fixed. @yiheng

**Pull request merged**
