### PR TITLE
add docker SNAPSHOT tag

### PR DESCRIPTION
**Pull request by Le-Zheng**
## Description

Add docker SNAPSHOT tag

### CODE REVIEW

**Comment by hkvision** [comment]
Will we still override the SNAPSHOT every day? How can we get the correspondence between SNAPSHOT and pip nightly version?

**Comment by Le-Zheng** [comment]
> Will we still override the SNAPSHOT every day? How can we get the correspondence between SNAPSHOT and pip nightly version?

@glorysdj @pinggao187 can we release nightly image tagged like intelanalytics/bigdl-k8s
:2.3.0b20230131 which is the same version as pypi? I'm a bit worried that it will increase space on Dockerhub.

**Comment by hkvision** [comment]
What's the status of this PR?

**Comment by Le-Zheng** [comment]
This pr will be merge for adding "SNAPSHOT" tag and will crate another pr for adding monthly docker release.

**Pull request merged**
