### PR TITLE
Add get sample method for ImageFrame

### PR DESCRIPTION
**Pull request by wzhongyuan**
## What changes were proposed in this pull request?
FIrst step to add python API - Add get sample method for ImageFrame
## How was this patch tested?
ut
## Related links or issues (optional)
fixed https://github.com/intel-analytics/BigDL/issues/2322

### CODE REVIEW

**Comment by wzhongyuan** [comment]
PR validation passed http://172.168.2.101:8080/job/BigDL-PR-Validation-v3/465/

**Comment by wzhongyuan** [comment]
I tested locally without any issue, will add some tests as well

**Comment by wzhongyuan** [comment]
@jenniew  just checked the code, it won't throw exception as what you saw is in abstract class, the implementation `ArraySample` still use it, Other python API also still relies on this as well

**Comment by jenniew** [comment]
LGTM

**Comment by wzhongyuan** [comment]
Ran another PR after adding test http://172.168.2.101:8080/job/BigDL-PR-Validation-v3/473/

**Pull request merged**
