### PR TITLE
[LLM] support loading q4_1/q5_0/q5_1/q8_0 gguf model

### PR DESCRIPTION
**Pull request by MeouSker77**
## Description

support loading q4_1/q5_0/q5_1/q8_0 gguf model

### CODE REVIEW

**Comment by MeouSker77** [comment]
For now, we have supported q4_0/q4_1/q5_0/q5_1/q8_0, which are supported by both llama.cpp and bigdl-llm.

While llama.cpp also has some other quantize methods which are not supported by bigdl-llm, such as q2_k, q3_k, q4_k, shall we support loading them ?

@jason-dai

**Comment by jason-dai** [comment]
> While llama.cpp also has some other quantize methods which are not supported by bigdl-llm, such as q2_k, q3_k, q4_k, shall we support loading them ?
> 
> @jason-dai

We can support it later; let's work out an end-to-end example first.

**Comment by MeouSker77** [comment]
> We can support it later; let's work out an end-to-end example first.

ok

**Review by rnwang04 — APPROVED** [review]
LGTM

**Pull request merged**
