### PR TITLE
Nano: quantization example from pytorch original code

### PR DESCRIPTION
**Pull request by zhentaocc**
Modify #4076 to show how to apply nano quantization on pytorch original code.

### CODE REVIEW

**Comment by yangw1234** [comment]
The description of the PR seems not the same as the code.

**Comment by zhentaocc** [comment]
> The description of the PR seems not the same as the code.

Missed one commit. Now it's ready.

**Comment by yangw1234** [comment]
How about separating the framework changes and example changes into two PRs? I think two PRs will make it more clear.

**Comment by zhentaocc** [comment]
> How about separating the framework changes and example changes into two PRs? I think two PRs will make it more clear.

Good idea.

**Comment by yangw1234** [comment]
LGTM

**Pull request merged**
