### PR TITLE
Refactor layer creation for keras

### PR DESCRIPTION
**Pull request by zhichao-li**
## What changes were proposed in this pull request?

- Rename createXX to createKerasXX.
- PythonBigDLKeras should inherit from PythonBigDL
## How was this patch tested?
unittest

### CODE REVIEW

**Comment by hkvision** [comment]
jenkins failed http://172.168.2.101:8080/view/PR-V(new)/job/BigDL-PR-Validation-v3/123/ pls check

**Comment by hkvision** [comment]
Also expose some methods such as `toTensor` from `PythonBigDL`

**Comment by zhichao-li** [comment]
those methods can be inherit from PythonBigDL

**Comment by hkvision** [comment]
jenkins passed http://172.168.2.101:8080/view/PR-V(new)/job/BigDL-PR-Validation-v3/125/

**Pull request merged**
