### PR TITLE
bump version to 0.8.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by wzhongyuan**
## What changes were proposed in this pull request?
bump version to 0.8.0-SNAPSHOT

## How was this patch tested?
UT
## Related links or issues (optional)
fixed https://github.com/intel-analytics/BigDL/issues/XXX

### CODE REVIEW

**Comment by yiheng** [comment]
I think you should bump version in core first...

**Comment by wzhongyuan** [comment]
core has been changed and approved by @i8run

**Comment by yiheng** [comment]
we should also update the link to core?

**Comment by wzhongyuan** [comment]
PR validation passed  http://mlt-bddl01.sh.intel.com:8080/job/BigDL-PRVN-lite/241/ 
Merging it now

**Comment by wzhongyuan** [comment]
PR validation passed  http://mlt-bddl01.sh.intel.com:8080/job/BigDL-PRVN-lite/241/ 
Merging it now

**Comment by wzhongyuan** [comment]
PR validation passed  http://mlt-bddl01.sh.intel.com:8080/job/BigDL-PRVN-lite/241/ 
Merging it now

**Comment by wzhongyuan** [comment]
PR validation passed, Merging it now

**Comment by wzhongyuan** [comment]
PR validation passed  http://mlt-bddl01.sh.intel.com:8080/job/BigDL-PRVN-lite/241/ 
Merging it now

**Comment by wzhongyuan** [comment]
PR validation passed, Merging it now
http://mlt-bddl01.sh.intel.com:8080/job/BigDL-PRVN-lite/241

**Pull request merged**
