### PR TITLE
Fix python ut with wrong format and precision

### PR DESCRIPTION
**Pull request by hkvision**
## What changes were proposed in this pull request?

Use np.testing.assert_allclose instead of docstring.

## How was this patch tested?

Jenkins

## Related links or issues (optional)
fixed https://github.com/intel-analytics/BigDL/issues/XXX

### CODE REVIEW

**Comment by zhichao-li** [comment]
looks good. we can merge this once pass in the new environment.

**Comment by hkvision** [comment]
old jenkins passed http://172.168.2.101:8080/job/BigDL-PR-V/851/

**Comment by hkvision** [comment]
new jenkins passed http://172.168.2.101:8080/view/PR-V(new)/job/BigDL-PRVN-pythontest-Spark-1.5/39/

**Comment by glorysdj** [comment]
LGTM, please merge:)

**Pull request merged**
