### PR TITLE
[nano] fix distributed training backend

### PR DESCRIPTION
**Pull request by Django-Jiang**
fix spawn model issue and add args check in trainer

### CODE REVIEW

**Comment by yangw1234** [comment]
let's also enable this test for spawn https://github.com/intel-analytics/BigDL/blob/main/python/nano/test/pytorch/tests/test_plugin.py#L78

**Comment by Django-Jiang** [comment]
> let's also enable this test for spawn https://github.com/intel-analytics/BigDL/blob/main/python/nano/test/pytorch/tests/test_plugin.py#L78

Test added

**Comment by yangw1234** [comment]
@TheaperDeng can we enforce the checkpoint path to be true for now?

**Comment by TheaperDeng** [comment]
> @TheaperDeng can we enforce the checkpoint path to be true for now?

yes we can, we are doing it in #4925

**Comment by TheaperDeng** [comment]
> > @TheaperDeng can we enforce the checkpoint path to be true for now?
> 
> yes we can, we are doing it in #4925

done

**Comment by yangw1234** [comment]
http://10.112.231.51:18888/view/BigDL-2.0-PR/job/BigDL-NanoTests-PR-Validation/262/

**Pull request merged**
