### PR TITLE
update unittest for dl_classifier

### PR DESCRIPTION
**Pull request by megaSpoon**
## What changes were proposed in this pull request?

unittest for dl_classifier

## How was this patch tested?

locally set SPARK_HOME to spark-1.5x and run python tests script which is passed successfully.

### CODE REVIEW

**Comment by megaSpoon** [comment]
I just closed the previous PR and put the next steps in the comments here:

From Zhichao:
Let's merge this once the Jenkins passed, and trigger nightlybuilt(http://172.168.2.101:8080/view/NightlyBuild/job/BigDL-Nightly-Build/) to test against Spark1.5.
@glorysdj should we add Spark1.5 verification back to Jenkins PR validation?

**Comment by megaSpoon** [comment]
I'm running the Jenkins test now. Once it is approved, I'll let you know @zhichao-li

**Comment by megaSpoon** [comment]
Jenkins passed. Running nightly-built against spark-1.5 now.

**Comment by zhichao-li** [comment]
@megaSpoon  looks good. backport to branch-0.3 as well?

**Pull request merged**
