### PR TITLE
Dllib: add `import subprocess` in spark.py

### PR DESCRIPTION
**Pull request by hamham223**
### 1. Why the change?

Test on k8s cluster mode failed:
```python
Traceback (most recent call last):
  File "/bigdl/nfsdata/yinchen/pytorch_train_spark_dataframe.py", line 31, in <module>
    init_orca(args.cluster_mode, extra_python_lib="process_spark_dataframe.py,"
  File "/bigdl/nfsdata/yinchen/utils.py", line 97, in init_orca
    sc = init_orca_context(cluster_mode="k8s-cluster",
  File "/usr/local/envs/py38/lib/python3.8/site-packages/bigdl/orca/common.py", line 311, in init_orca_context
    sc = init_spark_on_k8s_cluster(master=kwargs["master"],
  File "/usr/local/envs/py38/lib/python3.8/site-packages/bigdl/dllib/nncontext.py", line 406, in init_spark_on_k8s_cluster
    return_value = runner.init_spark_on_k8s_cluster(
  File "/usr/local/envs/py38/lib/python3.8/site-packages/bigdl/dllib/utils/spark.py", line 454, in init_spark_on_k8s_cluster
    return_value = subprocess.run(submit_command_list)
NameError: name 'subprocess' is not defined
```

add the import at the beginning of the two functions
previous pr: https://github.com/intel-analytics/BigDL/pull/8018

### 2. How to test?

- [x] test on k8s-cluster
- [x] test on yarn-cluster

### CODE REVIEW

**Comment by hamham223** [comment]
@ShanSimu Could you pla take a look? 👀

**Comment by ShanSimu** [comment]
have you tested?

**Comment by hamham223** [comment]
> have you tested?

Test success both in yarn-cluster and k8s-cluster mode.

**Review by ShanSimu — APPROVED** [review]
lgtm

**Pull request merged**
