### PR TITLE
Chronos: Update installation panel

### PR DESCRIPTION
**Pull request by liangs6212**
doc: https://liangs.readthedocs.io/en/enhance-chronos-installation-panel/doc/Chronos/Overview/install.html

### CODE REVIEW

**Comment by liangs6212** [comment]
doc: https://liangs.readthedocs.io/en/enhance-chronos-installation-panel/doc/Chronos/Overview/install.html

**Comment by TheaperDeng** [comment]
Should we disable the "Inference" option when user select "stable (2.1.0)"? 

Others LGTM

**Comment by TheaperDeng** [comment]
change "Inference" -> "Inference Optimization"

**Comment by liangs6212** [comment]
> Should we disable the "Inference" option when user select "stable (2.1.0)"?
> 
> Others LGTM


Actually, I have deleted the inference in the last commit, you can try to use `ctrl+F5` to refresh the page.
btw, It seems that `ctrl+F5` is more reliable than `F5`.

**Review by TheaperDeng — APPROVED** [review]

**Pull request merged**
