### PR TITLE
Support pyspark.sql.types.ArrayType with pyspark.sql.types.StringType elements

### PR DESCRIPTION
**Pull request by nyamashi**
Merge PR from analytics-zoo: https://github.com/intel-analytics/analytics-zoo/pull/5105

test result: ```test_array_string_input()```
```
[Row(id=0, input=['foo', 'qux', 'bar'], prediction=DenseVector([4.0, 3.0, 5.0])), Row(id=1, input=['qux', 'baz', 'baz'], prediction=DenseVector([3.0, 2.0, 2.0]))]
```

test env:
- python3.7.12
- ray==1.10.0
- tensorflow==2.3.0

### CODE REVIEW

**Review by hkvision — APPROVED** [review]

**Comment by hkvision** [comment]
jenkins passed: http://10.112.231.51:18888/view/BigDL-2.0-PR/job/BigDL-Orca-PR-Validation/417/
http://10.112.231.51:18888/job/ZOO-PR-BigDL-Python-Spark-3.1-py37-Horovod/534/consoleFull

**Comment by hkvision** [comment]
@nyamashi Thanks for your contribution and support! Look forward to more cooperation for recommendation :)

**Comment by nyamashi** [comment]
@hkvision 
Thank you for your support. 😄 
I'm preparing demos of zoo/bigdl with tensorflow recommenders and ranking using MovieLens dataset based on colabo.
I'll also try to use zoo/bigdl for the recommender systems in production.

**Comment by hkvision** [comment]
@nyamashi Great! It will be better to switch to BigDL as we are now contributing to this repo and you may be able to use the new features. Keep updated and tell me if you encounter any questions :)

**Comment by hkvision** [comment]
> @hkvision Got it! I'll use BigDL instead of Analytics-Zoo in the near future. The BigDL repo has colabo-notebook examples, so I'll easily try, extend and share it, thanks!

You are welcome! Thank you for using BigDL!

**Pull request merged**
