### PR TITLE
add LR example for DLClassifier and DLEstimator

### PR DESCRIPTION
**Pull request by hhbyyh**
## What changes were proposed in this pull request?

add LR implemented with BigDL, as examples for DLClassifier and DLEstimator

## How was this patch tested?
manual test.

### CODE REVIEW

**Comment by hhbyyh** [comment]
cc @jason-dai Shall we just move all the text in Readme to each of the example and remove the readme file?

also cc @wzhongyuan

**Comment by wzhongyuan** [comment]
@hhbyyh to keep consistent with other examples, Personally I think it's better to leave README file as it is.
BTW , please change the class name in the run command from "DLEstimatorLeNet" to "DLClassifierLeNet"

**Comment by hhbyyh** [comment]
Thanks for the review. 
And I mean we could remove the readme in all the examples and move them to the code.

**Comment by jason-dai** [comment]
Let's keep the readme for now

**Comment by hhbyyh** [comment]
Ack. @wzhongyuan The doc has been updated.

**Comment by jason-dai** [comment]
LGTM

**Comment by wzhongyuan** [comment]
LGTM

**Comment by hhbyyh** [comment]
Something is wrong with Jenkins PR validation right now. Will merge after a successful validation.

**Comment by hhbyyh** [comment]
PR validation passed: http://172.168.2.101:8080/job/BigDL-PR-Validation/1274/

**Pull request merged**
