### PR TITLE
Nano : InferenceOptimizer example about how to export the optimized model to standard format.

### PR DESCRIPTION
**Pull request by rnwang04**
## Description

 Bigdl-nano InferenceOptimizer example about how to export the optimized model to standard format.

### 1. Why the change?

We need to show users how to export the optimized model (which is obtained from InferenceOptimizer.get_best_model) to standard format.

### 2. User API changes

No change.

### 3. Summary of the change 

- [x] Bigdl-nano InferenceOptimizer example about how to export the optimized model to standard format.
- [x] other fix

### 4. How to test?
- [ ] Unit test
- [ ] Application test

### CODE REVIEW

**Comment by jason-dai** [comment]
Change folder name to `inference_optimizer`

**Comment by rnwang04** [comment]
> Change folder name to `inference_optimizer`

done, will change `inference_pipeline` to  `inference_optimizer`

**Comment by jason-dai** [comment]
LGTM

**Comment by rnwang04** [comment]
@jason-dai  any concern or comments about this? Do you think we should support onnxsim for openvino?

**Pull request merged**
