### PR TITLE
[Bug Fix] Fix Issue 2734

### PR DESCRIPTION
**Pull request by LeicongLi**
## What changes were proposed in this pull request?
Replace ZippedPartitionsLocalityPartition with zipPartition in Abstract Optimizer

## Related links or issues (optional)
fixed https://github.com/intel-analytics/BigDL/issues/2734

### CODE REVIEW

**Comment by wzhongyuan** [comment]
`ZipPartition` works , but I think we should fix bug in `ZippedPartitionsWithLocalityRDD`

**Comment by LeicongLi** [comment]
Jenkins result:
http://mlt-bddl01.sh.intel.com:8080/job/BigDL-PRVN-lite/585/

**Comment by wzhongyuan** [comment]
we need to test to see if it's fixed

**Comment by LeicongLi** [comment]
Jenkins test success
http://mlt-bddl01.sh.intel.com:8080/job/BigDL-PRVN-lite/627/

**Pull request merged**
