### PR TITLE
upgrade json-smart to 2.4.10

### PR DESCRIPTION
**Pull request by Uxito-Ada**
## Description

upgrade azure-identity to 1.81 for security scan by upgrading azure-sdk-bom to 1.2.11

### 1. Why the change?

Low-version azure-identity cannot pass security scan, and thus switch to the 1.81 one in azure-sdk-bom 1.2.11

### 4. How to test?
- [ ] N/A
- [x] Unit test
- [ ] Application test
- [ ] Document test
- [ ] ...

### CODE REVIEW

**Review by jenniew — COMMENTED** [review]
Did you test the e2e pipeline on Azure?

**Comment by Uxito-Ada** [comment]
> Did you test the e2e pipeline on Azure?

We will ensure security scan passed before testing

**Comment by Uxito-Ada** [comment]
exclude json-smart in azure-identity and depend json-smart 2.4.10 directly, instead of upgrading azure-sdk-bom

**Comment by Le-Zheng** [comment]
LGTM

**Review by Le-Zheng — APPROVED** [review]

**Pull request merged**
