### PR TITLE
change parameters order for channelnormalize to BGR

### PR DESCRIPTION
**Pull request by dding3**

### CODE REVIEW

**Comment by dding3** [comment]
jekins pass. http://10.112.231.51:18888/view/ZOO-PR/job/BigDL-PR-Dllib-Validation/247/

**Comment by jason-dai** [comment]
OpenCV uses BGR, and Pillow uses RGB; how can we support both cases?

**Comment by dding3** [comment]
We have some `transformer`s support convert BGR to RGB (eg. set `ImageMatToTensor(toRGB=True)`)?

**Comment by Litchilitchy** [comment]
Maybe we can add pillow and opencv-python related UT for this later?

**Pull request merged**
