### PR TITLE
Add Deepseek-6.7B

### PR DESCRIPTION
**Pull request by Zhangky11**
## Description
Add Deepseek-6.7B CPU and GPU examples

### CODE REVIEW

**Comment by Oscilloscope98** [comment]
Please also updated the readme for Windows GPU supports as we have done here: https://github.com/intel-analytics/BigDL/pull/9992

It would be better to have some verification on Windows GPU.

**Comment by Zhangky11** [comment]
I've updated README file and finished verifications on windows GPU.

**Comment by Zhangky11** [comment]
It can work when I set cpu_embedding=True for both HF-transformer API and Pytorch API.

**Comment by shane-huang** [comment]
please resolve conflicts.

**Comment by shane-huang** [comment]
> It can work when I set cpu_embedding=True for both HF-transformer API and Pytorch API.

Does `cpu_embedding=True` has negative impact for Arc? If not, maybe we can add this option in example code (so that iGPU can work well and Arc does not have negative impact)

**Review by shane-huang — APPROVED** [review]
LGTM

**Pull request merged**
