### PR TITLE
Refine file interface

### PR DESCRIPTION
**Pull request by wzhongyuan**
## What changes were proposed in this pull request?

1 ) Change FIle interface to make it more reusable 
2) Add module loader to leverage the newly exposed interface

## How was this patch tested?
1) Tested locally and unit test

### CODE REVIEW

**Comment by wzhongyuan** [comment]
ModuleLoader and Persister test cased will be added in seperate PRs as it relies on specific layer implementation

**Comment by wzhongyuan** [comment]
PR validation passed https://github.com/intel-analytics/spark-dl/pull/1447

**Comment by qiuxin2012** [comment]
LGTM

**Comment by wzhongyuan** [comment]
@qiuxin2012  Thanks for the review, am merging it now

**Pull request merged**
