### PR TITLE
Refactor Python API: model test to model evaluation

### PR DESCRIPTION
**Pull request by hkvision**
## What changes were proposed in this pull request?

Requested by issue #1580 
- Model evaluation in API in scala and python are not consistent -> change `model.test` to `model.evaluate` on python side.
- Provide a runnable code in python model evaluation docs so that users can run directly.

At the same time, fix issue #1627 (correct typo in docs) in master branch.

## How was this patch tested?

Jenkins.

### CODE REVIEW

**Comment by hkvision** [comment]
Remove duplicate definitions of evaluate(self) from pr #1534 and #1560

**Comment by hkvision** [comment]
Python doesn't support multiple methods with the same name but different arguments while Scala supports.
Reference:
https://stackoverflow.com/questions/34546775/two-functions-same-name-python
https://stackoverflow.com/questions/23707644/is-it-legal-to-define-two-methods-with-the-same-name-but-different-returning-typ/23707683

**Comment by hkvision** [comment]
Tested the updated docs locally.

**Comment by hkvision** [comment]
PR Validation passed: http://172.168.2.101:8080/view/PR-Validation/job/BigDL-PR-Validation/1985/

**Comment by yiheng** [comment]
LGTM

**Pull request merged**
