### PR TITLE
Nano: Change location of `benchmark/run.py`

### PR DESCRIPTION
**Pull request by hjzin**
### 1. Why the change?

We want to add some chronos workflow to the performance regression test, the current location of `python/nano/benchmark/run.py` is not suitable for adding chronos workflow, we need to move it out of the nano folder.
### 2. User API changes

To run `run.py`:
```bash
# before
python python/nano/benchmark/run.py resnet50

# later
python python/benchmark/run.py nano resnet50
```
### 3. Summary of the change 

1. Move python/nano/benchmark/run.py to python/benchmark/run.py
2. Update related path in performance-regression-test.yml

### CODE REVIEW

**Comment by hjzin** [comment]
APRT

**Comment by MeouSker77** [comment]
APRT

**Comment by glorysdj** [comment]
@MeouSker77 Your benchmark <https://github.com/intel-analytics/BigDL/pull/6484#issuecomment-1308265551> of workload `resnet_inference`             has finished, see <https://github.com/intel-analytics/BigDL/actions/runs/3425791329> for details

Use `uuid='55496020-5ff6-11ed-8125-86d8f8900f97'` to query the result

**Comment by glorysdj** [comment]
@MeouSker77 Your benchmark <https://github.com/intel-analytics/BigDL/pull/6484#issuecomment-1308265551> of workload `resnet50`             has finished, see <https://github.com/intel-analytics/BigDL/actions/runs/3425791329> for details

Use `uuid='42fbabe2-5ff8-11ed-812b-86d8f8900f97'` to query the result

**Pull request merged**
