### PR TITLE
Refine model name

### PR DESCRIPTION
**Pull request by zhichao-li**
## What changes were proposed in this pull request?
Previously the name of module is hardcode and cannot reflect the user input.
After the changes: 
```
        >>> conv2 = SpatialConvolution(6, 12, 5, 5).set_name("conv2")
        >>> print(conv2)
        conv2(6 -> 12, 5 x 5, 1, 1, 0, 0)
```

and use simple class name for the default value: ie. ``` com.intel.analytics.bigdl.nn.SoftMax@4df4dc0``` -> ``` SoftMax@4df4dc0```

## How was this patch tested?
manual

https://github.com/intel-analytics/BigDL/issues/893

### CODE REVIEW

**Comment by zhichao-li** [comment]
cc @shane-huang  @SeaOfOcean  @qiuxin2012  any comments?

**Comment by SeaOfOcean** [comment]
For SoftMax, getName will return com.intel.analytics.bigdl.nn.SoftMax@4df4dc0,
we should simplify it if no setName

**Comment by zhichao-li** [comment]
@SeaOfOcean  this has been addressed as well, let me update the description.

**Comment by yiheng** [comment]
I think it's different when you print the name and print the class.

If print the class, the class type, name and parameter; if print the name, should just return the name.

print class
```python
conv2 = SpatialConvolution(6, 12, 5, 5).set_name("conv2")
print(conv2)
com.intel.xxx.SpaitialConv[conv](6 -> 12, 5 x 5, 1, 1, 0, 0)
```

print name
```python
conv2 = SpatialConvolution(6, 12, 5, 5).set_name("conv2")
print(conv2.name)
conv2
```

**Comment by zhichao-li** [comment]
What this pr going to address is ``` print class ```, I'm going to change like this:
```
conv2 = SpatialConvolution(6, 12, 5, 5).set_name("conv2")
print(conv2)
```
```
com.intel.xxx.SpaitialConv(6 -> 12, 5 x 5, 1, 1, 0, 0) 
->
SpaitialConv[conv2](6 -> 12, 5 x 5, 1, 1, 0, 0) 
```

**Comment by zhichao-li** [comment]
cc @yiheng Just add a printName method which would responsible for the class printing. I'm going to merge this if no other comments.

**Comment by yiheng** [comment]
printName should only print name, right? __toString__ should print class

**Comment by zhichao-li** [comment]
No. getName would focus on the ``` name ``` itself (i.e. user can use this name to pinpoint a module), and ```printName``` is used to construct a printing format for a module.

**Comment by yiheng** [comment]
If you want to print the module, why not override this method in python? 

```python
def __str__(self):
```

**Comment by zhichao-li** [comment]
already did that.

**Comment by yiheng** [comment]
then why need the printName method? User can
```python
print(layer.getName)
```
right?

**Pull request merged**
