### PR TITLE
Add python API for new transformers and apply them in inception training example

### PR DESCRIPTION
**Pull request by wzhongyuan**
## What changes were proposed in this pull request?
Add python API for new transformers and apply them in inception training example

## How was this patch tested?
UT

## Related links or issues (optional)
fixed https://github.com/intel-analytics/BigDL/issues/XXX

### CODE REVIEW

**Comment by wzhongyuan** [comment]
@i8run  @zhangxiaoli73   Please help review thanks

**Comment by zhangxiaoli73** [comment]
Code LGTM.  imagenet dataset should be original, so you have to change tips about how to generate hadoop sequence file in readme.

**Comment by wzhongyuan** [comment]
@zhangxiaoli73   I remember we cannot generate seq file from original images, we need to manually hard code right ?  we should fix it in another PR

**Comment by wzhongyuan** [comment]
PR validation passed http://mlt-bddl01.sh.intel.com:8080/job/BigDL-PRVN-lite/249/

**Pull request merged**
