### PR TITLE
update pypi/spark version

### PR DESCRIPTION
**Pull request by pinggao187**

### CODE REVIEW

**Comment by pinggao187** [comment]
[#712](https://github.com/analytics-zoo/arda-docker/issues/712)

**Comment by Le-Zheng** [comment]
LGTM

**Comment by Le-Zheng** [comment]
Also need to modify to spark313 on branch-2.1

**Comment by pinggao187** [comment]
test pass
http://10.112.231.51:18889/view/BigDL-Release/job/BigDL2.0-Deploy-PYTHON-PyPI-Specific-Spark-Version/7/console

**Comment by leonardozcm** [comment]
lgtm

**Pull request merged**
