### PR TITLE
bigdl all in one jar

### PR DESCRIPTION
**Pull request by Le-Zheng**
## Description

Build one jar `bigdl-assembly-spark_2.4.6-2.1.0-SNAPSHOT-jar-with-dependencies.jar`
1. change bigdl-assembly packaging as jar
2. add plugin to append all dependencies and build one jar
3. remove single *jar-with-dependency in fat-assembly, and add all in one jar in fat-assembly
image

### CODE REVIEW

**Comment by Le-Zheng** [comment]
It looks the size is equal
image

**Comment by hkvision** [comment]
Will there be any place we can download this jar only instead of the fat zip? (e.g. for databricks we only need the jar)

**Review by glorysdj — APPROVED** [review]
LGTM

**Comment by Le-Zheng** [comment]
> Will there be any place we can download this jar only instead of the fat zip? (e.g. for databricks we only need the jar)

Yes, it will have an individual link for this jar.

**Comment by Le-Zheng** [comment]
> > Will there be any place we can download this jar only instead of the fat zip? (e.g. for databricks we only need the jar)
> 
> Yes, it will have an individual link for this jar.

jar link: https://oss.sonatype.org/content/repositories/snapshots/com/intel/analytics/bigdl/bigdl-assembly-spark_3.1.2/2.1.0-SNAPSHOT/bigdl-assembly-spark_3.1.2-2.1.0-20220912.135611-231-jar-with-dependencies.jar

**Pull request merged**
