### PR TITLE
transform python files in respect to comments

### PR DESCRIPTION
**Pull request by 122689305**
## What changes were proposed in this pull request?

transform into regular formats. Will add these format rules into jenkins

Can preview at http://172.168.2.168:5555

### CODE REVIEW

**Comment by 122689305** [comment]
@zhichao-li

**Comment by 122689305** [comment]
Rebase: finished
@zhichao-li

**Comment by zhichao-li** [comment]
@122689305 there are still conflicts need to be resolved.

**Comment by 122689305** [comment]
@zhichao-li rebased again

**Pull request merged**
