### PR TITLE
[PPML] fix remaining outdated variables

### PR DESCRIPTION
**Pull request by Uxito-Ada**
## Description

Fix remaining outdated variables in scripts and docs.

### 1. Why the change?

We need to give users a demo way to skip custom image building, and turn variable names in scripts more understandable.

### 2. User API changes

None.

### 3. Summary of the change 

fix remaining outdated variables in gramine.

### 4. How to test?
- [ ] N/A
- [x] Unit test
- [ ] Application test
- [x] Document test
- [ ] ...

### CODE REVIEW

**Comment by ShanSimu** [comment]
at the end of bigdl-ppml-submit.sh, there are still some 'commnd'

**Comment by Uxito-Ada** [comment]
Fixed @ShanSimu

**Comment by ShanSimu** [comment]
LGTM

**Review by ShanSimu — APPROVED** [review]
lgtm

**Pull request merged**
