### PR TITLE
[PPML] Add ppml Decrypt code

### PR DESCRIPTION
**Pull request by hzjane**
## Description
Add ppml Decrypt code

### CODE REVIEW

**Comment by Uxito-Ada** [comment]
Can we combine `Encrypt` and `Decrypt` into one and append an argument named `--action` instead of repeating codes?

**Comment by hzjane** [comment]
> Can we combine `Encrypt` and `Decrypt` into one and append an argument named `--action` instead of repeating codes?



> Can we combine `Encrypt` and `Decrypt` into one and append an argument named `--action` instead of repeating codes?

Good idea！

**Review by qiyuangong — APPROVED** [review]
LGTM

**Comment by Uxito-Ada** [comment]
Pls also modify *Encrypt and upload data* section in PPML README after `Encrypt` API is updated.

**Pull request merged**
