### PR TITLE
upgrade opencv to 4.2

### PR DESCRIPTION
**Pull request by Le-Zheng**

### CODE REVIEW

**Comment by dding3** [comment]
LGTM

**Comment by Le-Zheng** [comment]
This pr is merged first for unblocking deploy and jenkins test.
Please ignore the 4 UT error caused by OpenCV4.2:
JENKINS_ERROR

**Comment by Le-Zheng** [comment]
@Litchilitchy There are some errors when building Serving due to OpenCV upgrade.
```
[ERROR]
/opt/work/jenkins/workspace/BigDL-PRVN-keras-scala/scala/serving/src/main/scala/com/intel/analytics/bigdl/serving/http/domains.scala:178: value CV_LOAD_IMAGE_UNCHANGED is not a member of object org.opencv.imgcodecs.Imgcodecs
[ERROR]  OpenCVMethod.fromImageBytes(byteBuffer, Imgcodecs.CV_LOAD_IMAGE_UNCHANGED)

```
Could you please follow this pr to fix it? Need to change `CV_LOAD_IMAGE_UNCHANGED` to `IMREAD_UNCHANGED` in serving code.

**Comment by dding3** [comment]
Seems like orca jekins still blocked by `/opt/work/jenkins/workspace/ZOO-PR-BigDL-Python-Spark-2.4-py37-ray/scala/serving/src/main/scala/com/intel/analytics/bigdl/serving/preprocessing/PreProcessing.scala:124: value CV_LOAD_IMAGE_UNCHANGED is not a member of object org.opencv.imgcodecs.Imgcodecs`? `serving` module failed to compile
http://10.112.231.51:18888/job/ZOO-PR-BigDL-Python-Spark-2.4-py37-ray/885//console

**Comment by Le-Zheng** [comment]
> Seems like orca jekins still blocked by `/opt/work/jenkins/workspace/ZOO-PR-BigDL-Python-Spark-2.4-py37-ray/scala/serving/src/main/scala/com/intel/analytics/bigdl/serving/preprocessing/PreProcessing.scala:124: value CV_LOAD_IMAGE_UNCHANGED is not a member of object org.opencv.imgcodecs.Imgcodecs`? `serving` module failed to compile http://10.112.231.51:18888/job/ZOO-PR-BigDL-Python-Spark-2.4-py37-ray/885//console

Fix in https://github.com/intel-analytics/BigDL/pull/5104

**Pull request merged**
