### PR TITLE
Nano: add quantized model save&load API

### PR DESCRIPTION
**Pull request by TheaperDeng**
### Save and load
reference to https://pytorch.org/tutorials/beginner/saving_loading_models.html#saving-loading-model-for-inference

#### save
```python
# torch model
torch.save(model.state_dict(), PATH)  # fp32 pytorch model
torch.save(model.quantized_state_dict(), PATH)  # int8 pytorch model
```

#### load

since onnx file is easy to load we only consider torch model.

```python
# torch model
model = TheModelClass(*args, **kargs)
model = Trainer.compile(model)
model.load_state_dict(torch.load(PATH))  # fp32
model.load_quantized_state_dict(torch.load(PATH))  # int8
```

### CODE REVIEW

**Comment by TheaperDeng** [comment]
http://10.112.231.51:18888/job/ZOO-PR-NanoTests/211/
http://10.112.231.51:18888/job/Chronos-PR-Validation-Spark-3.1/299/

**Comment by TheaperDeng** [comment]
merge this PR and will change according to comments if any in next PR

**Comment by jason-dai** [comment]
- Currently the user will write the following code:
   ```python
   model = trainer.compile(model, loss, optimizer) #no need to set quantize=true
   mode = trainer.quantize(model, ...);
   ```
  and
   ```python
   model = trainer.compile(model, quantize=true) #need to set quantize=true
   mode.model.load_quantized_state_dict(...)
   ```

- I think we need make the APIs a little bit more consistent: either the user needs to set `quantize=true` in both cases, or the user does not need to set it at all.

**Comment by TheaperDeng** [comment]
> * Currently the user will write the following code:
>   ```python
>   model = trainer.compile(model, loss, optimizer) #no need to set quantize=true
>   mode = trainer.quantize(model, ...);
>   ```
>   
>   
>       
>         
>       
>   
>         
>       
>   
>       
>     
>   and
>   ```python
>   model = trainer.compile(model, quantize=true) #need to set quantize=true
>   mode.model.load_quantized_state_dict(...)
>   ```
> * I think we need make the APIs a little bit more consistent: either the user needs to set `quantize=true` in both cases, or the user does not need to set it at all.

I think I can make quantize methods always bonded to the model. But right now `quantize` parameter is set to `True` by default, users don't need to set it explicitly. Do we really need to remove this paramter?

**Comment by jason-dai** [comment]
> > * Currently the user will write the following code:
> >   ```python
> >   model = trainer.compile(model, loss, optimizer) #no need to set quantize=true
> >   mode = trainer.quantize(model, ...);
> >   ```
> >   
> >   
> >       
> >         
> >       
> >   
> >         
> >       
> >   
> >       
> >     
> >   and
> >   ```python
> >   model = trainer.compile(model, quantize=true) #need to set quantize=true
> >   mode.model.load_quantized_state_dict(...)
> >   ```
> > * I think we need make the APIs a little bit more consistent: either the user needs to set `quantize=true` in both cases, or the user does not need to set it at all.
> 
> I think I can make quantize methods always bonded to the model. But right now `quantize` parameter is set to `True` by default, users don't need to set it explicitly. Do we really need to remove this paramter?

Then why would the user set it to false?

**Comment by TheaperDeng** [comment]
> > > * Currently the user will write the following code:
> > >   ```python
> > >   model = trainer.compile(model, loss, optimizer) #no need to set quantize=true
> > >   mode = trainer.quantize(model, ...);
> > >   ```
> > >   
> > >   
> > >       
> > >         
> > >       
> > >   
> > >         
> > >       
> > >   
> > >       
> > >     
> > >   and
> > >   ```python
> > >   model = trainer.compile(model, quantize=true) #need to set quantize=true
> > >   mode.model.load_quantized_state_dict(...)
> > >   ```
> > > * I think we need make the APIs a little bit more consistent: either the user needs to set `quantize=true` in both cases, or the user does not need to set it at all.
> > 
> > 
> > I think I can make quantize methods always bonded to the model. But right now `quantize` parameter is set to `True` by default, users don't need to set it explicitly. Do we really need to remove this paramter?
> 
> Then why would the user set it to false?

neural-compressor is still not our forced requirement library for Nano. This parameter is for users who want to remove any redundant quantization-related monkey patch on their model since they don't need them. Once this happens, we can ask our users to turn this parameter to false.

**Comment by jason-dai** [comment]
> > > > * Currently the user will write the following code:
> > > >   ```python
> > > >   model = trainer.compile(model, loss, optimizer) #no need to set quantize=true
> > > >   mode = trainer.quantize(model, ...);
> > > >   ```
> > > >   
> > > >   
> > > >       
> > > >         
> > > >       
> > > >   
> > > >         
> > > >       
> > > >   
> > > >       
> > > >     
> > > >   and
> > > >   ```python
> > > >   model = trainer.compile(model, quantize=true) #need to set quantize=true
> > > >   mode.model.load_quantized_state_dict(...)
> > > >   ```
> > > > * I think we need make the APIs a little bit more consistent: either the user needs to set `quantize=true` in both cases, or the user does not need to set it at all.
> > > 
> > > 
> > > I think I can make quantize methods always bonded to the model. But right now `quantize` parameter is set to `True` by default, users don't need to set it explicitly. Do we really need to remove this paramter?
> > 
> > 
> > Then why would the user set it to false?
> 
> neural-compressor is still not our forced requirement library for Nano. This parameter is for users who want to remove any redundant quantization-related monkey patch on their model since they don't need them. Once this happens, we can ask our users to turn this parameter to false.

Then maybe you may bind quantization related methods on demand (i.e., when the user calls `quantize` or `load_quantized_state_dict`).

**Pull request merged**
