### PR TITLE
standard pr description

### PR DESCRIPTION
**Pull request by linbojin**
## What changes were proposed in this pull request?

- [x] add pr template

## How was this patch tested?

manual tests

## Related links or issues
ref: https://github.com/blog/2111-issue-and-pull-request-templates

### CODE REVIEW

**Comment by jason-dai** [comment]
@linbojin thanks for the PR - it makes a lot of sense. I wonder if you can append the following sentence to the template:
```
Please review https://github.com/intel-analytics/BigDL/blob/master/CONTRIBUTING.md before opening a pull request.
```

**Comment by linbojin** [comment]
@jason-dai because there is already a CONTRIBUTING.md file in this repo, so when we submit a pr, there is a similar sentence:

image

Do I still need to add your sentence?

**Comment by jason-dai** [comment]
I didn't notice that :-) In that case, there is no need to add that sentence.

**Comment by linbojin** [comment]
@jason-dai will you merge this pr?

**Comment by jason-dai** [comment]
@linbojin I wonder if you can help further simplify the template (e.g., similar to https://github.com/apache/spark/blob/master/.github/PULL_REQUEST_TEMPLATE) by:
1. Remove the "Benchmark" section
2. Change "Related links or issue" section to optional

**Comment by linbojin** [comment]
@jason-dai Updated

**Comment by jason-dai** [comment]
LGTM; merging the PR.

**Pull request merged**
