### PR TITLE
Chronos: make bigdl-chronos[all] option available

### PR DESCRIPTION
**Pull request by TheaperDeng**
## Description
remove openvino-dev since it has conflict (numpy version) with other dependencies which makes the `bigdl-chronos[all]` option not usable.

### CODE REVIEW

**Comment by TheaperDeng** [comment]
@liangs6212 please also have a look

**Comment by liangs6212** [comment]
LGTM

**Comment by plusbang** [comment]
LGTM

**Comment by TheaperDeng** [comment]
http://10.112.231.51:18889/job/BigDL-Chronos-PR-Validation/712/

**Pull request merged**
