### PR TITLE
fix mlp batch size check

### PR DESCRIPTION
**Pull request by MeouSker77**

### CODE REVIEW

**Review by gc-fu — APPROVED** [review]
I am doing a quick test with this PR using my workload.  It now worked normally when using `llama_mlp_forward` and not using `llama_mlp_forward`.  So LGTM.

Note: I only tested llama model.

**Review by rnwang04 — APPROVED** [review]
LGTM

**Comment by jason-dai** [comment]
Also need to fix https://github.com/intel-analytics/BigDL/pull/9709? @rnwang04

**Comment by rnwang04** [comment]
> Also need to fix #9709? @rnwang04

I think #9709 is ok for this, no need to fix it.

**Comment by jason-dai** [comment]
> > Also need to fix #9709? @rnwang04
> 
> I think #9709 is ok for this, no need to fix it.

It seems you are using different conditions to check; it might be better to refactor the logic into one utility method.

**Pull request merged**
