### PR TITLE
Distribute partition evenly on each node

### PR DESCRIPTION
**Pull request by yiheng**
In the training process, BigDL will issue one spark task on each node. Currently, we coalesce train data RDD with shuffle to node number to achieve this. But this is not safe, as the task scheduler can still schedule different partitions into a same node.  A solution is coalesce train data RDD to node number * core number with shuffle, so the data will distributed evenly on each node. Then coalesce without shuffle to node number. This is what the PR do.

### CODE REVIEW

**Comment by linbojin** [comment]
IMO, spark will schedule tasks based on partitions (one task for one partition) and for performance purpose, number of partitions should be 2 * cores for each node. `BigDL will issue one spark task on each node` is this designed by bigdl?

**Comment by yiheng** [comment]
@linbojin We do this only in training process to get a better performance. 

In the training process, because model need to sync parameter for mini-batch SGD and to reduce the thread context switch, bigdl will place one partition of train dataset on one node(which means bigdl will re-partition the training dataset to node number). So there's one computing task on one node.

Please note that it's only for training process. You can use bigdl model just as normal spark transformer in prediction. See this example: 
https://github.com/intel-analytics/BigDL/tree/master/dl/src/main/scala/com/intel/analytics/bigdl/example/imageclassification

**Comment by linbojin** [comment]
Make sense, thx for your explanation.

**Comment by yiheng** [comment]
Just clarify the root cause of the partition not distributed evenly among the cluster is the partition number is too small. The real fix is this line...

https://github.com/intel-analytics/BigDL/pull/353/files#diff-628659303f629f06eb48d9af1d343db7R293

The coalesce changes has been reverted in https://github.com/intel-analytics/BigDL/pull/368/commits/3f17840f814b7eb3b29bb486b7ce8fbd7ad22e15

Sorry for the confusion.

**Pull request merged**
