### PR TITLE
Nano: support an option to start process by "fork" on UNIX-like OS for multiprocessing training

### PR DESCRIPTION
**Pull request by TheaperDeng**
Since "fork" does not require any serialization, this might be a life-saver for our users who have
1. components that can not be serialized (e.g. `threading.Lock`)
2. closure (e.g. decorator)

I am not sure if current API design is the best.
Current:
```python
trainer = Trainer(distributed_backend="spawn", process_start_method="fork")
```
Is this confusing to our users? we may just create another backend called "fork" and make our users use it like:
```python
trainer = Trainer(distributed_backend="fork")
```
-------------------------
Update: 4/25: discussed with @yangw1234 
Will change this PR's implementation to 
```python
trainer = Trainer(distributed_backend="fork")
```
this design

### CODE REVIEW

**Comment by jason-dai** [comment]
Does fork work for Jupyter notebook @yangw1234 ?

**Comment by TheaperDeng** [comment]
need more experiment to verify if "fork" works just like "spawn" and does not have any side-effects.

**Comment by TheaperDeng** [comment]
There seems to be a dead lock issue if users don't use intel-openmp (i.e. not using `bigdl-nano-init`)

**Comment by TheaperDeng** [comment]
> Does fork work for Jupyter notebook @yangw1234 ?

Yes, just had a verification run.

**Comment by TheaperDeng** [comment]
This PR is on hold since deadlock problem is unsolved. https://pythonspeed.com/articles/python-multiprocessing/

**Pull request closed without merging**
