### PR TITLE
Add version specific to bigdl-nano

### PR DESCRIPTION
**Pull request by charlieJ107**
Added the identity of the specified version for the intel-tensorflow dependency of bigdl-nano.

### CODE REVIEW

**Comment by yangw1234** [comment]
LGTM, let's merge it after jenkins passed

**Comment by charlieJ107** [comment]
Jenkins passed at http://10.112.231.51:18888/job/ZOO-PR-nano-test/94/

**Comment by yangw1234** [comment]
you need to pass all tests here http://10.112.231.51:18888/job/ZOO-PR-NanoTests/

**Comment by charlieJ107** [comment]
Full test passed at http://10.112.231.51:18888/job/ZOO-PR-NanoTests/65/

**Pull request merged**
