### PR TITLE
remove gcc g++ in bigdl-k8s image

### PR DESCRIPTION
**Pull request by Le-Zheng**
image size is reduced from 1.51GB to 1.3GB

### CODE REVIEW

**Comment by Le-Zheng** [comment]
manual test passed with manual build image "10.239.45.10/arda/intelanalytics/bigdl-k8s-spark-3.1.2:2.1.0-SNAPSHOT-20220529-rmgcc".  
run spark_pandas.py with k8s cluster mode succeed

**Review by glorysdj — APPROVED** [review]
LGTM

**Comment by glorysdj** [comment]
please share the image size here.

**Comment by Le-Zheng** [comment]
> please share the image size here.

The current image size is 852.66 MB compressed on dockerhub

**Pull request merged**
