### PR TITLE
Tf2estimator on Pyspark backend log to driver

### PR DESCRIPTION
**Pull request by jenniew**

### CODE REVIEW

**Comment by yangw1234** [comment]
Is it possible to wrap the log forwarding logic into a single class and expose a few APIs to the estimator, so that other estimators can easily use that class without copying the code?

**Comment by jason-dai** [comment]
Why not move most of the logic to `LogMonitor`?

**Comment by jenniew** [comment]
> Why not move most of the logic to `LogMonitor`?

Yes, move most of logic to 'LogMonitor' under bigdl.orca.learn to be reused by other estimators.

**Comment by jenniew** [comment]
Jenkins: http://10.112.231.51:18888/view/ZOO-PR/job/BigDL-Orca-PR-Validation/208/

**Pull request merged**
