### PR TITLE
[Bigdl-Nano] Adapt nano test on jenkins

### PR DESCRIPTION
**Pull request by leonardozcm**

### CODE REVIEW

**Comment by leonardozcm** [comment]
http://10.112.231.51:18888/job/ZOO-NB-NanoTests/83/
And this pr will fix http://10.112.231.51:18888/job/ZOO-NB-nano-codestyle-test/93/console

**Comment by leonardozcm** [comment]
hi @yangw1234 , would you mind taking a look at this?

**Comment by yangw1234** [comment]
https://github.com/intel-analytics/BigDL/pull/3375 I already have a pr to address this.

**Comment by leonardozcm** [comment]
> #3375 I already have a pr to address this.

Great! I have aligned nano source-forge release job with bigdl-pip release, maybe you could reuse it.

**Pull request closed without merging**
