### PR TITLE
fix load caffe v1layer bug, load caffe layers only once in dynamic mode

### PR DESCRIPTION
**Pull request by SeaOfOcean**
## What changes were proposed in this pull request?

fix load caffe v1layer bug, load caffe layers only once in dynamic mode

## How was this patch tested?

unit test

### CODE REVIEW

**Comment by wzhongyuan** [comment]
I am a little confused here, if you can loadCaffeModel() from the companion object, each time a new instance of CaffeLoader will be created. is it going to be a problem ? what's the scenario that duplicated loading will happen ?

**Comment by SeaOfOcean** [comment]
createCaffeModel will loadCaffe, it will also call copyParameters (loadCaffe again)

**Comment by wzhongyuan** [comment]
I see, Not sure why but I just checked previous check-ins, there is a checking to avoid double loading

  private def loadCaffe(prototxtPath: String, modelPath: String): Unit = {
    if (name2LayerV2 == null) {
      netparam = loadBinary(prototxtPath, modelPath)
      name2LayerV2 = Map[String, LayerParameter]()
      name2LayerV1 = Map[String, V1LayerParameter]()
      import scala.collection.JavaConverters._
      // V1LayerParameter
      netparam.getLayersList.asScala.foreach(layer => name2LayerV1 += (layer.getName -> layer))
      // V2LayerParameter
      netparam.getLayerList.asScala.foreach(layer => name2LayerV2 += (layer.getName -> layer))

    }
  }

Can we do similarly to avoid declaring a new variable ? Maybe wen can check netparam to see if it's not null ?

**Comment by SeaOfOcean** [comment]
pr validate pass

**Comment by wzhongyuan** [comment]
LGTM

**Pull request merged**
