### PR TITLE
Dataset testing for nano keras multiprocessing training

### PR DESCRIPTION
**Pull request by az2181036**
Neither `multiprocessing backend` nor `ray backend` can work with dataset generates from `from_generator` API.

### CODE REVIEW

**Comment by yangw1234** [comment]
let's summarize your results in a table

**Comment by az2181036** [comment]
|                     API                      | results |                             link                             |
| :------------------------------------------: | :-----: | :----------------------------------------------------------: |
| image_dataset_from_directory (original demo) |  pass   |                              /                               |
|                    apply                     |  pass   | https://github.com/intel-analytics/BigDL/blob/7fb777a932dc428a40184a4acf0b28a438d2c12d/python/nano/example/tensorflow/test.py#L172 |
|              from_tensor_slices              |  pass   | https://github.com/intel-analytics/BigDL/blob/7fb777a932dc428a40184a4acf0b28a438d2c12d/python/nano/example/tensorflow/test.py#L64 |
|                from_generator                |  fail   | https://github.com/intel-analytics/BigDL/blob/7fb777a932dc428a40184a4acf0b28a438d2c12d/python/nano/example/tensorflow/test.py#L26 |
|             using `py_function`              |  fail   | https://github.com/intel-analytics/BigDL/blob/7fb777a932dc428a40184a4acf0b28a438d2c12d/python/nano/example/tensorflow/test.py#L92 |
|            using `numpy_function`            |  fail   | https://github.com/intel-analytics/BigDL/blob/7fb777a932dc428a40184a4acf0b28a438d2c12d/python/nano/example/tensorflow/test.py#L128 |
|                    filter                    |  pass   | https://github.com/intel-analytics/BigDL/blob/7fb777a932dc428a40184a4acf0b28a438d2c12d/python/nano/example/tensorflow/test.py#L164 |
|                 concatenate                  |  pass   | https://github.com/intel-analytics/BigDL/blob/7fb777a932dc428a40184a4acf0b28a438d2c12d/python/nano/example/tensorflow/test.py#L158 |
|             choose_from_datasets             |  pass   | https://github.com/intel-analytics/BigDL/blob/7fb777a932dc428a40184a4acf0b28a438d2c12d/python/nano/example/tensorflow/test.py#L151 |

**Comment by az2181036** [comment]
Partially completed.

**Comment by az2181036** [comment]
|                     API                      | results |                             link                             |
| :------------------------------------------: | :-----: | :----------------------------------------------------------: |
| image_dataset_from_directory (original demo) |  pass   |                              /                               |
|                    apply                     |  pass   | https://github.com/intel-analytics/BigDL/blob/4d00fbfa0be7a2e3f476069ae936bc311c1ed4d7/python/nano/example/tensorflow/test.py#L167 |
|                choice_dataset                |  pass   | https://github.com/intel-analytics/BigDL/blob/4d00fbfa0be7a2e3f476069ae936bc311c1ed4d7/python/nano/example/tensorflow/test.py#L145 |
|                 concatenate                  |  pass   | https://github.com/intel-analytics/BigDL/blob/4d00fbfa0be7a2e3f476069ae936bc311c1ed4d7/python/nano/example/tensorflow/test.py#L154 |
|                    filter                    |  pass   | https://github.com/intel-analytics/BigDL/blob/4d00fbfa0be7a2e3f476069ae936bc311c1ed4d7/python/nano/example/tensorflow/test.py#L161 |
|                   flat_map                   |  pass   | https://github.com/intel-analytics/BigDL/blob/4d00fbfa0be7a2e3f476069ae936bc311c1ed4d7/python/nano/example/tensorflow/test.py#L175 |
|               use_py_function                |  fail   | https://github.com/intel-analytics/BigDL/blob/4d00fbfa0be7a2e3f476069ae936bc311c1ed4d7/python/nano/example/tensorflow/test.py#L70 |
|               use_np_function                |  fail   | https://github.com/intel-analytics/BigDL/blob/4d00fbfa0be7a2e3f476069ae936bc311c1ed4d7/python/nano/example/tensorflow/test.py#L103 |
|                from_generator                |  fail   | https://github.com/intel-analytics/BigDL/blob/4d00fbfa0be7a2e3f476069ae936bc311c1ed4d7/python/nano/example/tensorflow/test.py#L19 |
|              from_tensor_slices              |  pass   | https://github.com/intel-analytics/BigDL/blob/4d00fbfa0be7a2e3f476069ae936bc311c1ed4d7/python/nano/example/tensorflow/test.py#L36 |
|               group_by_window                |  pass   | https://github.com/intel-analytics/BigDL/blob/4d00fbfa0be7a2e3f476069ae936bc311c1ed4d7/python/nano/example/tensorflow/test.py#L187 |
|                  interleave                  |  pass   | https://github.com/intel-analytics/BigDL/blob/4d00fbfa0be7a2e3f476069ae936bc311c1ed4d7/python/nano/example/tensorflow/test.py#L224 |
|                 padded_batch                 |  pass   | https://github.com/intel-analytics/BigDL/blob/4d00fbfa0be7a2e3f476069ae936bc311c1ed4d7/python/nano/example/tensorflow/test.py#L201 |
|             sample_from_dataset              |  pass   | https://github.com/intel-analytics/BigDL/blob/4d00fbfa0be7a2e3f476069ae936bc311c1ed4d7/python/nano/example/tensorflow/test.py#L208 |
|                    shard                     |  pass   | https://github.com/intel-analytics/BigDL/blob/4d00fbfa0be7a2e3f476069ae936bc311c1ed4d7/python/nano/example/tensorflow/test.py#L218 |
|                   snapshot                   |  fail   | https://github.com/intel-analytics/BigDL/blob/4d00fbfa0be7a2e3f476069ae936bc311c1ed4d7/python/nano/example/tensorflow/test.py#L239 |
|                 with_options                 |  pass   | https://github.com/intel-analytics/BigDL/blob/4d00fbfa0be7a2e3f476069ae936bc311c1ed4d7/python/nano/example/tensorflow/test.py#L251 |

**Pull request closed without merging**
