### PR TITLE
Chronos: Modify tf2 model UTs

### PR DESCRIPTION
**Pull request by liangs6212**
## Description

conflict with installation options and fix known issues.

### CODE REVIEW

**Review by TheaperDeng — COMMENTED** [review]
we may delete tf1 uts since all the external API is deprecated.

**Comment by TheaperDeng** [comment]
others LGTM

**Comment by liangs6212** [comment]
http://10.112.231.51:18889/view/BigDL-PR-Validation/job/BigDL-Chronos-PR-Validation/781

**Review by TheaperDeng — APPROVED** [review]
LGTM

**Comment by TheaperDeng** [comment]
maybe rebase this PR and run github action again so that we could merge it

**Pull request merged**
