### PR TITLE
[LLM] Integrate FastChat as a serving framework for BigDL-LLM

### PR DESCRIPTION
**Pull request by gc-fu**
## Description

This PR tries to integrate FastChat as a serving framework for `BigDL-LLM`.

The user will now be able to use FastChat as a service for `BigDL-LLM` transformer-int4 models.

### 1. Why the change?

To provide FastChat as a serving framework for `BigDL-LLM`.

### 2. User API changes

Detailed User API changes (from original FastChat) is listed in the `README.md` file in this PR.

### 3. Summary of the change 

We use patch to register `BigDL-LLM adapter` as a useful backend for `FastChat`.  The patch is applied when `model_worker` is executed.

### 4. How to test?
- [x] Manually test

### 5. New dependencies

- [x] New Python dependencies
       - fschat[model_worker] >= 0.2.24
       - protobuf

The reason why we need `fschat` is quite clear.

We need `protobuf` because this error

`UnboundLocalError: local variable 'sentencepiece_model_pb2' referenced before assignment` will occur if user sets `legacy = False`

### CODE REVIEW

**Comment by jason-dai** [comment]
Can we also run it on a laptop/desktop?

**Comment by gc-fu** [comment]
> Can we also run it on a laptop/desktop?

I have not tested it on laptop/desktop yet.  I will later do the test and report back the result.

**Comment by jason-dai** [comment]
> > Can we also run it on a laptop/desktop?
> 
> I have not tested it on laptop/desktop yet. I will later do the test and report back the result.

We can also try GPU (Arc) support

**Comment by gc-fu** [comment]
> > > Can we also run it on a laptop/desktop?
> > 
> > 
> > I have not tested it on laptop/desktop yet. I will later do the test and report back the result.
> 
> We can also try GPU (Arc) support

I have validated it on GPU (Arc).  It can run using XPU, but some modifications are required.  I will later push the changes to this PR.

**Comment by Uxito-Ada** [comment]
Does `pip install --pre --upgrade bigdl-llm[serving]` install the fschat in az repo? Can I add my features directly in the az repo?

**Comment by yangw1234** [comment]
any plan to support continuous batch (token level scheduling)?

**Review by glorysdj — APPROVED** [review]
LGTM

**Pull request merged**
