### PR TITLE
torch object detection tutorial

### PR DESCRIPTION
**Pull request by songhappy**
## Description

add a notebook for pytorch object detection

### CODE REVIEW

**Comment by leonardozcm** [comment]
@hkvision hi, would you mind taking a look at this?

**Comment by jenniew** [comment]
I think you may add prediction part to let user see the training result.

**Review by jenniew — COMMENTED** [review]
I think you may add prediction part to let user see the training result.

**Review by jenniew — APPROVED** [review]
LGTM

**Pull request merged**
