### PR TITLE
[Fix]add race condtion fix in spark 1.6

### PR DESCRIPTION
**Pull request by wzhongyuan**
## What changes were proposed in this pull request?
To make it compatible with spark_1.6 and scala 2.10 where scala.reflect is not thread safe

## How was this patch tested?
unit test and model validation job

## Related links or issues (optional)
fixed https://github.com/intel-analytics/BigDL/issues/XXX

### CODE REVIEW

**Comment by wzhongyuan** [comment]
@yiheng   please help review, I successfully ran the example without any issue now

**Comment by wzhongyuan** [comment]
PR validation passed http://172.168.2.101:8080/job/BigDL-PR-Validation-v3/337/

**Comment by wzhongyuan** [comment]
@yiheng   Any comments ? I just ran another PR to test against latest master code just in case.
http://172.168.2.101:8080/job/BigDL-PR-Validation-v3/345/

**Comment by yiheng** [comment]
Is it possible we add a sync lock outside ```doSerializeModule```

**Comment by wzhongyuan** [comment]
@yiheng   I know what you mean, that will make the code less to get changed, but we will loose kind of efficiency and not that flexible, right ?

**Comment by yiheng** [comment]
It's not only about less change. I think user may forget to add the lock when define the ser code in a new module

**Comment by wzhongyuan** [comment]
@yiheng   Refined as per discussion,

Ran another PR successfully http://172.168.2.101:8080/job/BigDL-PR-Validation-v3/358/

**Comment by wzhongyuan** [comment]
@yiheng   Any other comments ? thanks

**Pull request merged**
