### PR TITLE
Chronos: support building windows distribution in nightly build

### PR DESCRIPTION
**Pull request by hjzin**
### 1. Why the change?

To build chronos on windows and upload to pypi in nightly build and release, we need to update some build scripts.
### 2. User API changes

N/A
### 3. Summary of the change 

1. Update some build scripts to support build chronos windows distribution and upload to pypi
2. Disable `distributed` option when building Chronos on Windows

### CODE REVIEW

**Comment by Le-Zheng** [comment]
@leonardozcm @hkvision could you help to take a look?

**Comment by leonardozcm** [comment]
LGTM, and shall we also test it on **testpypi** like orca do before we merge this? @Le-Zheng

**Comment by Le-Zheng** [comment]
> LGTM, and shall we also test it on **testpypi** like orca do before we merge this? @Le-Zheng

That's a great point. It's better to validate via test pypi.

**Comment by hjzin** [comment]
> > LGTM, and shall we also test it on **testpypi** like orca do before we merge this? @Le-Zheng
> 
> That's a great point. It's better to validate via test pypi.

How can I validate it?

**Review by hkvision — APPROVED** [review]

**Comment by hjzin** [comment]
validate by publishing it to` test pypi`
http://10.112.231.51:18888/job/BigDL2.0-Deploy-PYTHON-PyPI-Specific-Spark-Version/lastBuild/

**Pull request merged**
