### PR TITLE
fix adapter issue

### PR DESCRIPTION
**Pull request by yiheng**
## What changes were proposed in this pull request?
This PR fixes two issues of Adapter:
1. When the configuration tensors of the adapter changes, an error will be thrown. It should rebuild the module
2. The adapter can't be serialized and de-serialized, as it contains a function member. This is fixed by use class inherent instead of function member

## How was this patch tested?
unit test
## Related links or issues (optional)
fixed https://github.com/intel-analytics/BigDL/issues/1813 and https://github.com/intel-analytics/BigDL/issues/1815

### CODE REVIEW

**Comment by yiheng** [comment]
jenkins pass

**Comment by wzhongyuan** [comment]
@yiheng  Can we add serialization tested for tf related layer/ops ? Maybe we need to open another issue

**Comment by yangw1234** [comment]
LGTM

**Comment by yiheng** [comment]
@wzhongyuan I prefer to open a new issue to track this. https://github.com/intel-analytics/BigDL/issues/1868

**Pull request merged**
