### PR TITLE
llm: benchmark tool for transformers int4 (separate 1st token and rest)

### PR DESCRIPTION
**Pull request by rnwang04**
## Description

Provide a simple benchmark tool for transformer int4 model by simply updating original generation utils file.

### 1. Why the change?

To provide a simple benchmark tool for transformer int4 model to calculate 1st token performance and the rest.
Now just put this file under **dev** directory for **internal usage**.

### 2. User API changes
Just warp your transformer int4 model with BenchmarkWrapper to obtain 1st token and rest performance.
```python
import torch
import os
from bigdl.llm.transformers import AutoModel
from transformers import AutoTokenizer
import time
import numpy as np
from .dev.benchmark_first_token import BenchmarkWrapper

model_path ='THUDM/chatglm-6b'
model = AutoModel.from_pretrained(model_path, trust_remote_code=True, load_in_4bit=True)
model = BenchmarkWrapper(model)
tokenizer = AutoTokenizer.from_pretrained(model_path, trust_remote_code=True)
 
with torch.inference_mode():
    input_ids = tokenizer.encode(prompt, return_tensors="pt")
    output = model.generate(input_ids, do_sample=False, max_new_tokens=1024)
    output_str = tokenizer.decode(output[0], skip_special_tokens=True)
```
output looks like:
```bash
=========First token cost x.xxxs=========
=========Last token cost average 0.xxxxs (xx tokens in all)=========
```

### 3. Summary of the change 

- simple benchmark wrapper for transformer int4 model to benchmark 1st token and the rest

### 4. How to test?
- [x] Local test
- [x] Unit test

### CODE REVIEW

**Review by plusbang — APPROVED** [review]
LGTM

**Comment by jason-dai** [comment]
Add a readme or example

**Comment by rnwang04** [comment]
> Add a readme or example

Have added a simple readme.

**Comment by jason-dai** [comment]
LGTM

**Pull request merged**
