### PR TITLE
[Orca] Fix Cifar10 Test Stuck in Jenkin Mac Job

### PR DESCRIPTION
**Pull request by pinggao187**

### CODE REVIEW

**Comment by pinggao187** [comment]
[[mac] orca cifar10 test stuck #630](https://github.com/intel-analytics/arda-docker/issues/630)

**Comment by pinggao187** [comment]
cifar10 test pass
http://10.112.231.51:18888/job/BigDL-PR-Orca-Python-ExampleTests-Ray-py36-py37-Mac/3/console

**Comment by sgwhat** [comment]
Others LGTM.

**Comment by pinggao187** [comment]
pass
http://10.112.231.51:18888/view/mac-job/job/BigDL-PR-Orca-Python-ExampleTests-Ray-py36-py37-Mac/5/console

**Comment by hkvision** [comment]
Why do we need this change?
Since this example is migrated from pytorch, the change should be as few as possible.

**Comment by pinggao187** [comment]
> Why do we need this change? Since this example is migrated from pytorch, the change should be as few as possible.

macosx | Cocoa rendering in OSX windows (presently lacks blocking show() behavior when matplotlib is in non-interactive mode)
cifar10 test stuck on https://github.com/intel-analytics/BigDL/blob/6e022fa56ec62f2bf2cfdcad9cc81544be823741/python/orca/example/learn/pytorch/cifar10/cifar10.py#L103

**Pull request merged**
