### PR TITLE
DLEstimator: add validation data and train/validation summary support

### PR DESCRIPTION
**Pull request by hhbyyh**
## What changes were proposed in this pull request?
Improvement for DLEstimator and DLClassifier:

1. add support for validation dataset
2. add support for training summary
3. add support for validation summary
4. and EndWhen to support different types of Trigger

## How was this patch tested?

new unit test added

### CODE REVIEW

**Comment by hhbyyh** [comment]
http://172.168.2.101:8080/job/BigDL-PR-V/705/ passed

**Comment by yiheng** [comment]
LGTM. Do we need to update the doc page?

**Comment by hhbyyh** [comment]
Thanks @yiheng for the review. 
I'll send the documents and example update in a follow-up PR so we don't have to review this again.

**Comment by hhbyyh** [comment]
http://172.168.2.101:8080/job/BigDL-PR-V/717/ passed

**Pull request merged**
