### PR TITLE
Caffe layer wise unit test

### PR DESCRIPTION
**Pull request by wzhongyuan**
## What changes were proposed in this pull request?

Add unit tests for caffe layer conversion

## How was this patch tested?

Unit test and local tests

## Related links or issues (optional)
fixed https://github.com/intel-analytics/BigDL/issues/1379

### CODE REVIEW

**Comment by wzhongyuan** [comment]
PR validation passed
http://172.168.2.101:8080/job/BigDL-PR-Validation/2230/

**Comment by zhichao-li** [comment]
Should we add unittest for `BinaryThreshold`? or it has been conver by on python side?

**Comment by wzhongyuan** [comment]
@zhichao-li  it's already covered by the added test

**Comment by zhichao-li** [comment]
LTGM

**Pull request merged**
