### PR TITLE
Add some more input/output docs to convolutions, rnns, recursive nns

### PR DESCRIPTION
**Pull request by psyyz10**
## What changes were proposed in this pull request?
Add some more input/output docs to convolutions, rnns, recursive nns
## Related links or issues (optional)
fixed https://github.com/intel-analytics/BigDL/issues/1478

### CODE REVIEW

**Comment by helenlly** [comment]
Does the doc change apply to v0.2 and 0.1?

**Comment by psyyz10** [comment]
@helenlly Shengsheng said that merge it to master, for more details, please ask her :)

**Comment by psyyz10** [comment]
@dding3 Review changed

**Comment by dding3** [comment]
LGTM

**Pull request merged**
