### PR TITLE
Orca: add batch_size arguments to model.fit()

### PR DESCRIPTION
**Pull request by lalalapotter**
## Description
This PR is to add `batch_size` arguments while calling function `model.fit()` in tensorflow 2.x estimator, which is to support the mlflow tracking.

### CODE REVIEW

**Comment by hkvision** [comment]
Comment: in our implementation, we input tf dataset which is already batched. Adding the batch size is mainly used for mlflow tracking, the batch size is the same as the batch in tf dataset, which should have no issue.

**Review by hkvision — APPROVED** [review]

**Comment by jason-dai** [comment]
> the batch size is the same as the batch in tf dataset, which should have no issue.

How do you enforce that?

**Comment by hkvision** [comment]
> > the batch size is the same as the batch in tf dataset, which should have no issue.
> 
> How do you enforce that?

The batch size argument in fit will be used to batch the tf dataset, will also be fed into fit. They will always be the same. Should have no issue?

**Comment by hkvision** [comment]
Seems for tf-distributed backend, local batch size for each worker is input_batch_size / worker_size?
But for pytorch, the input_batch_size is the batch size for every single worker?

**Pull request closed without merging**
