### PR TITLE
Fix SerializationUtils clone issue of QuantizedTensor

### PR DESCRIPTION
**Pull request by jenniew**
Fix SerializationUtils clone issue of QuantizedTensor.

### CODE REVIEW

**Comment by jason-dai** [comment]
Do we have a unit test for the issue?

**Comment by jenniew** [comment]
OptimPredictorShutdownSpec can test broadcasting of quantized tensor, but we only have local mode test.

**Comment by jason-dai** [comment]
> OptimPredictorShutdownSpec can test broadcasting of quantized tensor, but we only have local mode test.

Shall we add an integration test for "pseudo" cluster testing then? @Le-Zheng

**Comment by Le-Zheng** [comment]
We only have several UTs running on yarn. We may need to add this UT in the [integration test  scripts](https://github.com/intel-analytics/BigDL/blob/master/spark/dl/src/test/integration-test.robot#L93).

**Comment by jason-dai** [comment]
> We only have several UTs running on yarn. We may need to add this UT in the [integration test scripts](https://github.com/intel-analytics/BigDL/blob/master/spark/dl/src/test/integration-test.robot#L93).

Yes, we need to add it.

**Pull request merged**
