### PR TITLE
[Issue 450] add PropagateBackSwitch to disable some layers back propagation

### PR DESCRIPTION
**Pull request by SeaOfOcean**
## What changes were proposed in this pull request?

add PropagateBackSwitch to disable some layers back propagation

## How was this patch tested?

unit test
## Related links or issues (optional)
https://github.com/intel-analytics/BigDL/issues/450

### CODE REVIEW

**Comment by zhichao-li** [comment]
I was thinking if only want to disable backward, could we just simply add the the flag in ```AbstractModule.backward``` to control that?

**Comment by SeaOfOcean** [comment]
That's one choice, but the problem is that the backward may be override, it is not easy to control the behavior in this case

**Comment by zhichao-li** [comment]
For my understanding, ```backward``` is kind of like prototype method, we might not want to override it. In theory, customized logic can always go to  ```updateGradInput``` or ```accGradParameters``` if required.
Anyway, I'm ok to add another layer for this but its just too much at the first glance.

**Comment by yiheng** [comment]
@zhichao-li There's an issue for make backward final #25

**Comment by yiheng** [comment]
where is your test files

**Comment by SeaOfOcean** [comment]
BackwardSwitchSpec

**Pull request closed without merging**
