### PR TITLE
[LLM] Change build system from centos7 to ubuntu18.04

### PR DESCRIPTION
**Pull request by hoshibara**
## Description

Migrate the compilation work from centos7 to ubuntu18.04 to avoid the problems of [tokenization failed](https://github.com/analytics-zoo/nano/issues/467#issuecomment-1664932334), invalid `fPIC` flag and[ installation failed of python](https://github.com/intel-analytics/BigDL/pull/8677/files#diff-d6fd0abed5172fe778b21a79d644bfcdf675cf45efdf19a0f9c3eca5e39b3913).

### CODE REVIEW

**Comment by hoshibara** [comment]
The linux avx vnni binary fails to build correctly on Ubuntu 18.04.
it throws error:
```log
[  2%] Building C object src/llama/CMakeFiles/ggml-llama.dir/__/ggml.c.o
/tmp/ccy2JVJx.s: Assembler messages:
/tmp/ccy2JVJx.s:1273: Error: no such instruction: `{vex} vpdpbusd %ymm3,%ymm5,%ymm2'
/tmp/ccy2JVJx.s:1282: Error: no such instruction: `{vex} vpdpbusd %ymm3,%ymm5,%ymm2'
/tmp/ccy2JVJx.s:14[43](https://github.com/intel-analytics/BigDL/actions/runs/5759607928/job/15614000012?pr=8686#step:6:44): Error: no such instruction: `{vex} vpdpbusd %ymm8,%ymm7,%ymm3'
/tmp/ccy2JVJx.s:1[45](https://github.com/intel-analytics/BigDL/actions/runs/5759607928/job/15614000012?pr=8686#step:6:46)1: Error: no such instruction: `{vex} vpdpbusd %ymm7,%ymm1,%ymm3'
/tmp/ccy2JVJx.s:1508: Error: no such instruction: `{vex} vpdpbusd %ymm8,%ymm7,%ymm3'
/tmp/ccy2JVJx.s:1515: Error: no such instruction: `{vex} vpdpbusd %ymm7,%ymm0,%ymm3'
/tmp/ccy2JVJx.s:1590: Error: no such instruction: `{vex} vpdpbusd %ymm13,%ymm1,%ymm11'
/tmp/ccy2JVJx.s:1602: Error: no such instruction: `{vex} vpdpbusd %ymm13,%ymm0,%ymm12'
/tmp/ccy2JVJx.s:1673: Error: no such instruction: `{vex} vpdpbusd %ymm12,%ymm1,%ymm10'
/tmp/ccy2JVJx.s:1685: Error: no such instruction: `{vex} vpdpbusd %ymm12,%ymm0,%ymm11'
make[2]: *** [src/llama/CMakeFiles/ggml-llama.dir/__/ggml.c.o] Error 1
src/llama/CMakeFiles/ggml-llama.dir/build.make:75: recipe for target 'src/llama/CMakeFiles/ggml-llama.dir/__/ggml.c.o' failed
```
This error also occurs on ubuntu 20.04. But on 22.04 the binaries compile fine. However, the operating system version is too new, which may cause compatibility issues.
Maybe we can try centos 8.

**Comment by hoshibara** [comment]
The docker image for Centos 8 has been discontinued for 2 years.
Almalinux 8 is a good alternative to centos 8. I will try to build a docker runner image with it.

**Comment by hoshibara** [comment]
On Almalinux 8, the binaries compile correctly.
I tested:
- [x]  ~Centos 7~
image
- [x] Ubuntu 18.04
image
- [x] Ubuntu 20.04
image
- [x] Ubuntu 22.04
image

**Comment by hoshibara** [comment]
`file` command output:
```log
root@e8e80f9fe3d4:/home/runner/tmp-test# for file in *; do
>     if [ -f "$file" ]; then
>         echo "File: $file"
>         file "$file"
>         echo "==================================================="
>     fi
> done
File: libbloom-api.so
libbloom-api.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=0effc1805f7698af8abd54878547e12e4700b9c7, not stripped
===================================================
File: libbloom_avxvnni.so
libbloom_avxvnni.so: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, BuildID[sha1]=544b13367315940e3ef3cc4dcc09c32df772bc09, not stripped
===================================================
File: libgptneox-api.so
libgptneox-api.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=1bdcb59ff8bb54f918907ae47ac9c97ef89b735c, not stripped
===================================================
File: libgptneox_avxvnni.so
libgptneox_avxvnni.so: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, BuildID[sha1]=dde5617bb5e0a72a04f298d390cfa74260252ccc, not stripped
===================================================
File: libllama-api.so
libllama-api.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=3287c4862fc2e810c5b8de252c4b36779a144dfb, not stripped
===================================================
File: libllama_avxvnni.so
libllama_avxvnni.so: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, BuildID[sha1]=3579416c06e22ab247e2c557ef3604c3f95bb08f, not stripped
===================================================
File: libstarcoder-api.so
libstarcoder-api.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=331e5d9050ee5f8b367f1f6cbbe0fad598e6fd89, not stripped
===================================================
File: libstarcoder_avxvnni.so
libstarcoder_avxvnni.so: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, BuildID[sha1]=4e782ff574de1651fdce7bb6193619e3db6c43be, not stripped
===================================================
File: main-bloom
main-bloom: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=3e2d720f2097f75d48d1e36e7dda8e30903cbdb0, for GNU/Linux 3.2.0, not stripped, too many notes (256)
===================================================
File: main-chatglm_vnni
main-chatglm_vnni: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=0e3f8e7a6fc1c78a2b7fe06176139743cee707b1, for GNU/Linux 3.2.0, not stripped
===================================================
File: main-gptneox
main-gptneox: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=3fd1f7ef97bef579374eed129c37a37ba99f2fdc, for GNU/Linux 3.2.0, not stripped, too many notes (256)
===================================================
File: main-llama
main-llama: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=cae8098642f1dce97aecfe1643dcb1c469997247, for GNU/Linux 3.2.0, not stripped, too many notes (256)
===================================================
File: main-starcoder
main-starcoder: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=4938c4b9eb193864bc30764fce3192fe1832fdf8, for GNU/Linux 3.2.0, not stripped, too many notes (256)
===================================================
File: quantize-bloom
quantize-bloom: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=067988ea43a89afa7510bbdaa722a2982d8dede8, for GNU/Linux 3.2.0, not stripped
===================================================
File: quantize-gptneox
quantize-gptneox: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=0db6aa89f53ea5cee1dc9d2e5bb076e98b2a2aa4, for GNU/Linux 3.2.0, not stripped
===================================================
File: quantize-llama
quantize-llama: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=540bd383314c9f012925be2914cc7f346e06eb4c, for GNU/Linux 3.2.0, not stripped
===================================================
File: quantize-starcoder
quantize-starcoder: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=2a3f91164aaa5d43c4d06d18baae0fe80309d414, for GNU/Linux 3.2.0, not stripped
===================================================
```

**Review by MeouSker77 — APPROVED** [review]
LGTM after fixing the action fail

**Pull request merged**
