### PR TITLE
Change default learning rate for DLEstimator

### PR DESCRIPTION
**Pull request by hhbyyh**
## What changes were proposed in this pull request?

Since we have changed the default optimizer to SGD, we should set default learning rate to 1e-3.

update the unit test accordingly. Also use LBFGS in some unit tests to speed it up. (SGD takes much longer).

Add copy method to DLClassifier to support Grid Search.

## How was this patch tested?

existing unit tests

### CODE REVIEW

**Comment by hhbyyh** [comment]
@jenniew @jason-dai have we cut the release?

**Comment by jason-dai** [comment]
LGTM

**Comment by hhbyyh** [comment]
PR validation not available for now. Jenkins may run out of space.

http://172.168.2.101:8080/job/BigDL-PR-Validation-tf-caffe/70/console

**Comment by hhbyyh** [comment]
PR validation passed:
 http://172.168.2.101:8080/job/BigDL-PR-Validation/2074/

**Pull request merged**
