### PR TITLE
[LLM] Fix build error of bigdl-llm-cpu

### PR DESCRIPTION
**Pull request by Jasonzzt**

### CODE REVIEW

**Comment by Jasonzzt** [comment]
error:
```
/bin/sh: 1: cd: can't cd to ./intel-extension-for-pytorch
```
So remove irrelevant `cd`

**Comment by Zhengjin-Wang** [comment]
LGTM

**Review by Zhengjin-Wang — COMMENTED** [review]
LGTM

**Review by Zhengjin-Wang — APPROVED** [review]
LGTM

**Pull request merged**
