### PR TITLE
Nano: Original Pytorch example fro quantization- MNIST ConvNet

### PR DESCRIPTION
**Pull request by zhentaocc**
An example for #3901 
This is completely from https://github.com/pytorch/examples/blob/master/mnist/main.py
A second PR will follow to do some changes to show how nano and quantization are applied on pytorch code.

Pytorch License is here https://github.com/pytorch/pytorch/blob/master/LICENSE

- [x] - Add BigDL header
- [x] -  Add Pytorch header

### CODE REVIEW

**Comment by zhentaocc** [comment]
Any instructions on how to place the pytorch license? @yangw1234

**Comment by yangw1234** [comment]
> Any instructions on how to place the pytorch license? @yangw1234

Maybe you should add this license:
https://github.com/pytorch/examples/blob/master/LICENSE

**Comment by zhentaocc** [comment]
Having tested this script. Works fine on local cpu.

**Comment by zhentaocc** [comment]
http://10.112.231.51:18888/job/ZOO-PR-NanoTests/309/

**Comment by yangw1234** [comment]
LGTM

**Pull request merged**
