### PR TITLE
Friesian: fix ut `test_table` http time out

### PR DESCRIPTION
**Pull request by hamham223**
### 1. Why the change?
Fix https://github.com/analytics-zoo/arda-docker/issues/806 .

### 2. Summary of the change 

Download the model from ftp.

### 3. How to test?
Two PR-tests.

- [x] Friesian-Python-Py37-Spark3
- [x] Friesian-Python-Py37-Spark3-Pip

### CODE REVIEW

**Comment by hkvision** [comment]
Need to change the file path in the ut as well

**Comment by hamham223** [comment]
> Need to change the file path in the ut as well

seemly not? if the model is under the same directory. let's have a try first 😄

**Comment by hamham223** [comment]
(～￣▽￣)～ passed!!!! Happy April Fool!

**Comment by hamham223** [comment]
The model is a bit large(~ 500M). Do we need to delete it after the ut?

**Comment by hkvision** [comment]
> The model is a bit large(~ 500M). Do we need to delete it after the ut?

Yes, let's delete this after completion.

**Comment by hamham223** [comment]
downloading is a bit slow 55..

```bash
194150K .......... .......... .......... .......... .......... 87%  135K 3m17s
194200K .......... .......... .......... .......... .......... 87%  173K 3m17s
194250K .......... .......... .......... .......... .......... 87%  194K 3m16s
```

**Review by hkvision — APPROVED** [review]

**Pull request merged**
