### PR TITLE
use new rms norm

### PR DESCRIPTION
**Pull request by MeouSker77**
## Description

use new rms norm

### CODE REVIEW

**Review by rnwang04 — APPROVED** [review]
LGTM

**Comment by hkvision** [comment]
This PR doesn't pass the unit tests: https://github.com/intel-analytics/BigDL/actions/runs/8246492638/job/22552952279
Please make sure all the tests are passed before you merge your PR.

**Comment by MeouSker77** [comment]
action failed because it used a new API from bigdl-core-xe-21, but action will use latest nightly bigdl-core-xe-21, not main branch codeof bigdl-core-xe-21, there is no way to avoid such problems unless we change BigDL's action to build bigdl-core-xe-21 in action instead of using nightly bigdl-core-xe-21

**Comment by liu-shaojun** [comment]
@MeouSker77 
So tonight's test with today's nightly bigdl-core-xe-21 will run successfully because it includes the new API, right?

**Comment by MeouSker77** [comment]
yes, this action failed because it has no new API. 

yesterday's nightly test already had new API, it failed because qwen's rms norm error became larger.

**Comment by hkvision** [comment]
> action failed because it used a new API from bigdl-core-xe-21, but action will use latest nightly bigdl-core-xe-21, not main branch code of bigdl-core-xe-21, there is no way to avoid such problems unless we change BigDL's action to build bigdl-core-xe-21 in action instead of using nightly bigdl-core-xe-21

To avoid this problem, if the PR in BigDL is not that urgent, can wait for the next morning to merge after the new core-xe releases?

**Comment by MeouSker77** [comment]
> To avoid this problem, if the PR in BigDL is not that urgent, can wait for the next morning to merge after the new core-xe releases?

yes, this is a solution

**Pull request merged**
