### PR TITLE
Chronos : How to generate confidence interval for prediction

### PR DESCRIPTION
**Pull request by rnwang04**
## Description

Provide a How-to guide for new function: predict_interval in Forecaster

### 1. Why the change?

Provide a How-to guide for new function: predict_interval in Forecaster

### 2. User API changes

No change.

### 3. Summary of the change 

Provide a How-to guide for new function: predict_interval in Forecaster

### 4. How to test?
- [x] Colab test
- [x] Application test
- [x] Document test
https://ruonantetdoc.readthedocs.io/en/generate_confidence_interval/doc/Chronos/Howto/index.html
https://ruonantetdoc.readthedocs.io/en/generate_confidence_interval/doc/Chronos/Howto/how_to_generate_confidence_interval_for_prediction.html

### CODE REVIEW

**Comment by TheaperDeng** [comment]
1. Replace
> In time series area, [here](https://arxiv.org/abs/1709.01907) is a way to implement confidence interval based on Monte Carlo dropout.

to
> In time series area, we adopt Monte Carlo dropout to calculate confidence interval with a reference to [this paper](https://arxiv.org/abs/1709.01907).

2. For the last code block
```python
# obtain prediction and variation by predict_interval
yhat, std = forecaster.predict_interval(data=test_data,
                                        validation_data=val_data)
# obtain the upper bound and lower bound of interval according yhat and std
z_95 = 1.96 # for 95% confidence, check other quantile value of a standard Normal for other quantile
yhat_upper, yhat_lower = yhat + z_95 * std, yhat - z_95 *std
```

**Comment by rnwang04** [comment]
> 1. Replace
> 
> > In time series area, [here](https://arxiv.org/abs/1709.01907) is a way to implement confidence interval based on Monte Carlo dropout.
> 
> to
> 
> > In time series area, we adopt Monte Carlo dropout to calculate confidence interval with a reference to [this paper](https://arxiv.org/abs/1709.01907).
> 
> 2. For the last code block
> 
> ```python
> # obtain prediction and variation by predict_interval
> yhat, std = forecaster.predict_interval(data=test_data,
>                                         validation_data=val_data)
> # obtain the upper bound and lower bound of interval according yhat and std
> z_95 = 1.96 # for 95% confidence, check other quantile value of a standard Normal for other quantile
> yhat_upper, yhat_lower = yhat + z_95 * std, yhat - z_95 *std
> ```

done

**Comment by TheaperDeng** [comment]
only one comment
1. the `exit()` in installation code block (may) be removed since we had some test earlier, the issue caused us add this trick has now be resolved on google side.

**Comment by rnwang04** [comment]
> only one comment
> 
> 1. the `exit()` in installation code block (may) be removed since we had some test earlier, the issue caused us add this trick has now be resolved on google side.

done

**Pull request merged**
