### PR TITLE
[Nano] Openvino model inference notebook example with Nano

### PR DESCRIPTION
**Pull request by hjzin**
### 1. Why the change?
Add fundamental notebook examples to show how to run sync and async inference on OpenVINO model using Nano.

### 2. User API changes

N/A

### 3. Summary of the change 

Add fundamental notebook examples to show how to run sync and async inference on OpenVINO model using Nano.
Related issue: #5773 
### 4. How to test?
- [ ] Unit test

### CODE REVIEW

**Comment by hjzin** [comment]
need some change after #5615 is merged, because the output format of `model(x)` is changed in that PR.

**Comment by hjzin** [comment]
Example: https://zhaojie-doc.readthedocs.io/en/nano-notebook-example-openvinoir/doc/Nano/Howto/index.html#openvino

**Comment by TheaperDeng** [comment]
1. The code snip (i.e. `code snip`) does not work in a bold text, may find a way to fix it.
2. Should we suggest users what this API doing is basically "predict in parallel"?
> Each asynchronous infer request will run inference independently in asynchronous mode, and 5 inference results will be returned together in a list.

**Comment by hjzin** [comment]
> 2. Should we suggest users what this API doing is basically "predict in parallel"?
> 
> > Each asynchronous infer request will run inference independently in asynchronous mode, and 5 inference results will be returned together in a list.

Good idea, I will simplify the explanation.

**Review by TheaperDeng — APPROVED** [review]
LGTM

**Pull request merged**
