### PR TITLE
change engine's required configuration to warning

### PR DESCRIPTION
**Pull request by qiuxin2012**
#3351

### CODE REVIEW

**Comment by qiuxin2012** [comment]
change to warning's output
```
(nzoo) xin@xin-dev:~/IntelAnalytics/BigDL$ pyspark
Python 3.7.11 (default, Jul 27 2021, 14:32:16) 
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
21/11/02 10:11:24 WARN util.Utils: Your hostname, xin-dev resolves to a loopback address: 127.0.0.1; using 10.239.158.150 instead (on interface enp0s31f6)
21/11/02 10:11:24 WARN util.Utils: Set SPARK_LOCAL_IP if you need to bind to another address
21/11/02 10:11:24 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /__ / .__/\_,_/_/ /_/\_\   version 2.4.6
      /_/

Using Python version 3.7.11 (default, Jul 27 2021 14:32:16)
SparkSession available as 'spark'.
>>> from bigdl.dllib.utils.engine import get_bigdl_jars
Prepending /opt/anaconda3/envs/nzoo/lib/python3.7/site-packages/bigdl/share/dllib/conf/spark-bigdl.conf to sys.path
>>> jars = get_bigdl_jars()
>>> spark = SparkSession.builder.getOrCreate()
>>> spark._jsparkSession.sessionState().resourceLoader().addJar(jars[0])
>>> spark._jsparkSession.sessionState().resourceLoader().addJar(jars[1])
>>> from bigdl.orca.common import *
>>> init_orca_context(cluster_mode="spark-submit")
Initializing orca context
21/11/02 10:12:14 WARN utils.Engine$: Engine.init: Can not find spark.shuffle.reduceLocality.enabled. For details please check https://bigdl-project.github.io/master/#APIGuide/Engine/
21/11/02 10:12:14 WARN utils.Engine$: Engine.init: Can not find spark.shuffle.blockTransferService. For details please check https://bigdl-project.github.io/master/#APIGuide/Engine/
21/11/02 10:12:14 WARN utils.Engine$: Engine.init: Can not find spark.scheduler.minRegisteredResourcesRatio. For details please check https://bigdl-project.github.io/master/#APIGuide/Engine/
21/11/02 10:12:14 WARN utils.Engine$: Engine.init: Can not find spark.scheduler.maxRegisteredResourcesWaitingTime. For details please check https://bigdl-project.github.io/master/#APIGuide/Engine/
21/11/02 10:12:14 WARN utils.Engine$: Engine.init: Can not find spark.speculation. For details please check https://bigdl-project.github.io/master/#APIGuide/Engine/
21/11/02 10:12:14 WARN utils.Engine$: Engine.init: Can not find spark.serializer. For details please check https://bigdl-project.github.io/master/#APIGuide/Engine/
cls.getname: com.intel.analytics.bigdl.dllib.utils.python.api.Sample
BigDLBasePickler registering: bigdl.dllib.utils.common  Sample
cls.getname: com.intel.analytics.bigdl.dllib.utils.python.api.EvaluatedResult
BigDLBasePickler registering: bigdl.dllib.utils.common  EvaluatedResult
cls.getname: com.intel.analytics.bigdl.dllib.utils.python.api.JTensor
BigDLBasePickler registering: bigdl.dllib.utils.common  JTensor
cls.getname: com.intel.analytics.bigdl.dllib.utils.python.api.JActivity
BigDLBasePickler registering: bigdl.dllib.utils.common  JActivity
<SparkContext master=local[*] appName=PySparkShell>
>>> 
>>> 
```

**Comment by qiuxin2012** [comment]
Test on inception.py shows spark's default configuration `spark.shuffle.reduceLocality.enabled=true` is a little faster than `spark.shuffle.reduceLocality.enabled=false`, so I delete spark.shuffle.reduceLocality.enabled.

**Comment by dding3** [comment]
Please try to run lenet example after set spark.shuffle.reduceLocality.enabled=false, if the change works for small dataset. I think it's OK to make this change.

**Comment by qiuxin2012** [comment]
> Please try to run lenet example after set spark.shuffle.reduceLocality.enabled=false, if the change works for small dataset. I think it's OK to make this change.

The default value is true, I have delete the `spark.shuffle.reduceLocality.enabled=false`, and test on full inception on 20 executors and lenet5 example on 20 executors. The two test all passed.

**Pull request merged**
