### PR TITLE
Tf2 estimator optimize for predict

### PR DESCRIPTION
**Pull request by jenniew**
related issue: https://github.com/analytics-zoo/orca/issues/115
https://github.com/analytics-zoo/orca/issues/137

### CODE REVIEW

**Comment by hkvision** [comment]
How many batch calculations are needed for predict now to infer the schema when converting back to DataFrame?

**Comment by jenniew** [comment]
> How many batch calculations are needed for predict now to infer the schema when converting back to DataFrame?

Only one shard will be calculated.

**Comment by jenniew** [comment]
> How many batch calculations are needed for predict now to infer the schema when converting back to DataFrame?

Only one shard will be predicted.

**Comment by hkvision** [comment]
> > How many batch calculations are needed for predict now to infer the schema when converting back to DataFrame?
> 
> Only one shard will be predicted.

One shard means only one batch right? Since we set shard_size=batch_size.

**Comment by jenniew** [comment]
> > > How many batch calculations are needed for predict now to infer the schema when converting back to DataFrame?
> > 
> > 
> > Only one shard will be predicted.
> 
> One shard means only one batch right? Since we set shard_size=batch_size.

yes

**Pull request merged**
