### PR TITLE
Make tensor support boolean, short, int, long, string, char

### PR DESCRIPTION
**Pull request by psyyz10**
## What changes were proposed in this pull request?
Make tensor support boolean, short, int, long, string, char

### CODE REVIEW

**Comment by yiheng** [comment]
LGTM

**Comment by yiheng** [comment]
Add some unit test?

**Comment by yiheng** [comment]
@dding3 what do you think?

**Comment by psyyz10** [comment]
@yiheng Add some new operations and corresponding tests

**Comment by dding3** [comment]
Could you give some explanation about why do we need support boolean and string for tensor?

**Comment by psyyz10** [comment]
@dding3 for supporting tensorflow operations, such as readers for string and logicalOr and logicalAnd for boolean and so on.

**Pull request merged**
