### PR TITLE
Fix failures in python tests

### LINKED ISSUE #1621: Failures in Python unit tests on Jenkins
It seems that in on Jenkins, there are always Failures in some Python tests. However, the result always saya BUILD SUCCESS.

1. http://10.239.47.211:18888/job/BigDL-Nightly-Build-UnitTests-1.6-python/170/console
Several tests are not passed every time.
Fix the failures.
2. Figure out the configurations of Jenkins why it says success even if there are failure test cases.
Wrong exit status given.

#1623 and #1631 together will resolve this issue.

### PR DESCRIPTION
**Pull request by hkvision**
## What changes were proposed in this pull request?

To fix #1621 Item1

### CODE REVIEW

**Comment by hkvision** [comment]
Not sure about the following two changes:
class Bilinear(Model)  ->  class Bilinear(Layer)
class BifurcateSplitTable(Model)  ->  class BifurcateSplitTable(Layer)

**Comment by hkvision** [comment]
In the first commit, the four failed unit tests passed.

**Comment by hkvision** [comment]
Still some failures in other test cases to be fixed.

**Comment by hkvision** [comment]
Fixed TestSimple:saveGraphTopology failure.

**Comment by hkvision** [comment]
map(lambda (features, label): Sample.from_ndarray(features, label))
This syntax is invalid in Python 3.5
https://stackoverflow.com/questions/15712210/python-3-2-lambda-syntax-error

**Comment by hkvision** [comment]
Jenkins PR validation passed. http://172.168.2.101:8080/view/PR-Validation/job/BigDL-PR-Validation/1965/

**Comment by yiheng** [comment]
LGTM

**Pull request merged**
