### PR TITLE
LLM: Support GQA on llama kvcache

### PR DESCRIPTION
**Pull request by leonardozcm**
## Description

reasons see: https://github.com/analytics-zoo/nano/issues/563#issuecomment-1711373979

### CODE REVIEW

**Comment by yangw1234** [comment]
how about rebasing on this pr https://github.com/intel-analytics/BigDL/pull/8928

**Comment by leonardozcm** [comment]
> how about rebasing on this pr #8928

Of course

**Comment by leonardozcm** [comment]
llama2-70b
```log
(changmim-llm) cpx@cpx-2:/disk1/changmin/BigDL$ python int4_benchmark.py --repo-id llama2-70b --qtype sym_int4
-------------------- llama2-70b (transformers int4) --------------------
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 15/15 [01:27<00:00,  5.81s/it]
>> loading of model costs 118.19620275497437s
input length is :  32
/home/cpx/miniconda3/envs/changmim-llm/lib/python3.9/site-packages/transformers/generation/utils.py:1270: UserWarning: You have modified the pretrained model configuration to control generation. This is a deprecated strategy to control generation and will be removed soon, in a future version. Please use a generation configuration file (see https://huggingface.co/docs/transformers/main_classes/text_generation )
  warnings.warn(
>> Inference time: 19.615487575531006 s
>> Prompt: Once upon a time, there existed a little girl who liked to have adventures. She wanted to go to places and meet new people, and have fun
>> Output: Once upon a time, there existed a little girl who liked to have adventures. She wanted to go to places and meet new people, and have fun. She was a curious girl, and she loved to learn new things.
```

**Review by lalalapotter — APPROVED** [review]
LGTM

**Pull request merged**
