### PR TITLE
Chronos : How to preprocess my data guide

### PR DESCRIPTION
**Pull request by rnwang04**
## Description

Guide about how to preprocess my data.

### 1. Why the change?

HowTo guide.

### 2. User API changes

No change.

### 3. Summary of the change 

Guide about how to preprocess my data.

### 4. How to test?
- [x] Document test
https://ruonantetdoc.readthedocs.io/en/how_to_preprocess_my_data/doc/Chronos/Howto/how_to_preprocess_my_data.html

### CODE REVIEW

**Comment by TheaperDeng** [comment]
1. we need to show how does df looks like to users

2. if your data is stored in Prometheus.

3. show what does the internal df looks like after the processing

**Comment by rnwang04** [comment]
> 1. we need to show how does df looks like to users
> 2. if your data is stored in Prometheus.
> 3. show what does the internal df looks like after the processing

Done, could you please take a look again?

**Comment by Oscilloscope98** [comment]
You could add codes:
```css
/* for tables in notebooks generated by pandas dataframe */
.rendered_html table {
    table-layout: auto !important;
}
```
at the end of file [`BigDL/docs/readthedocs/source/_static/css/custom.css`](/home/pyuwen/BigDL/docs/readthedocs/source/_static/css/custom.css) to fix the strange table behavior :D

**Comment by rnwang04** [comment]
> You could add code:
> 
> ```css
> /* for tables in notebooks generated by pandas dataframe */
> .rendered_html table {
>     table-layout: auto !important;
> }
> ```
> 
> at the end of file [`BigDL/docs/readthedocs/source/_static/css/custom.css`](https://github.com/intel-analytics/BigDL/blob/main/docs/readthedocs/source/_static/css/custom.css) to fix the strange table behavior :D

Thanks!! It works.

**Pull request merged**
