### PR TITLE
Add CPU and GPU examples of phi-2

### PR DESCRIPTION
**Pull request by pengyb2001**
## Description

In this PR, I add CPU and GPU examples of Phi-2 using bigdl-llm's transformer and optimize_model API.
This is the issue page: https://github.com/analytics-zoo/nano/issues/976

### CODE REVIEW

**Comment by Oscilloscope98** [comment]
Please also updated the readme for Windows GPU supports as we have done here: https://github.com/intel-analytics/BigDL/pull/9992

It would be better to have some verification on Windows GPU.

**Comment by shane-huang** [comment]
Also update the tables in BigDL/README.md and BigDL/python/llm/README.md

**Comment by pengyb2001** [comment]
> Also update the tables in BigDL/README.md and BigDL/python/llm/README.md

Updated.

**Comment by shane-huang** [comment]
LGTM.

**Comment by shane-huang** [comment]
please resolve the conflicts.

**Review by shane-huang — APPROVED** [review]

**Pull request merged**
