### PR TITLE
Nano: Update the Nano installation panel

### PR DESCRIPTION
**Pull request by liangs6212**
## Description

Sync nano setup
doc link: https://liangs.readthedocs.io/en/nano-installation-panel-tf2/doc/Nano/Overview/install.html

### CODE REVIEW

**Comment by TheaperDeng** [comment]
1. The version section in installation panel for PT and TF is somehow different (one from 1.13 ->1.10, the other from 2.7 -> 2.10)
2. Move M-series chip installation guide to final paragraph and change it to.
```python
# any way to install tensorflow on macos
pip install --pre --upgrade bigdl-nano[tensorflow]
```
3. There is some typo `bigdl-chronos` -> `bigdl-nano`

**Comment by TheaperDeng** [comment]
there is an update for PT=1.10 case. We may add a channel inside the cmd `-f https://software.intel.com/ipex-whl-stable` for ipex installation. @rnwang04 please correct me if I miss anything.

**Comment by rnwang04** [comment]
> 

1. Maybe we should change to PT 1.10 -> 1.13
2. Shall we change this line
`conda create -n env python=3.8`
to
`conda create -n env python=3.8 setuptools==58.0.4` like workflow file?  @TheaperDeng

**Comment by TheaperDeng** [comment]
> > 
> 
> 1. Maybe we should change to PT 1.10 -> 1.13
Yeah, I am fine with both.

> 2. Shall we change this line
>    `conda create -n env python=3.8`
>    to
>    `conda create -n env python=3.8 setuptools==58.0.4` like workflow file?  @TheaperDeng
We won't need this line any more since we have changed the installation step for M-series chip. But this reminds me, if we need to put 3.8/3.9 support note on this page? @MeouSker77

**Comment by rnwang04** [comment]
Shall we recommend CentOS as we already know openvino 2022.x does not support CentOS anymore. @TheaperDeng

**Comment by rnwang04** [comment]
others LGTM.

**Pull request merged**
