### PR TITLE
Add version suffix to spark3 release

### LINKED ISSUE #3070: Spark 3 with Scala 2.12
Hi devs!

Not an issue but a question (feel free to add the label):

Given that Spark 3 has been released now a few month ago, do you have any plans to go for it and update to Spark 3 which also needs to move to Scala 2.12?
I'm also wondering if this [Spark 3 deployment script](https://github.com/intel-analytics/BigDL/blob/master/scripts/deploy-spark3.sh) can work with the current version still being on Scala 2.11

Thanks in advance.

### PR DESCRIPTION
**Pull request by hkvision**
Fix #3070 #3323 #3845

### CODE REVIEW

**Comment by hkvision** [comment]
Tested locally. Will release after log4j issue gets resolved.

**Comment by jason-dai** [comment]
Need to update user guide too

**Comment by hkvision** [comment]
> Need to update user guide too

Seems spark3 suffix is not valid for pypi version... still trying to seek for alternative solutions...

**Comment by hkvision** [comment]
Since suffix for version is not doable for pypi, closing this PR.

**Pull request closed without merging**
