### PR TITLE
Remove the code dealing with translating tensorflow NHWC format to BigDL NCHW format

### PR DESCRIPTION
**Pull request by yangw1234**
## What changes were proposed in this pull request?

Refactor and rm the code dealing with translating tensorflow NHWC format to BigDL NCHW format

## How was this patch tested?

existing tests and manually tested

### CODE REVIEW

**Comment by yiheng** [comment]
LGTM

**Comment by yiheng** [comment]
what about the testing?

**Comment by yiheng** [comment]
looks like the tf env is ot enabled on jenkins. @glorysdj 
>python or tensorflow is not installed (TensorflowSpecHelper.scala:36)

**Comment by yangw1234** [comment]
pr validation pass

**Pull request merged**
