### PR TITLE
fix jackson-databind Vulnerability

### PR DESCRIPTION
**Pull request by Le-Zheng**
## Description

Upgrade jackson in dllib

### CODE REVIEW

**Comment by Le-Zheng** [comment]
http://10.112.231.51:18888/job/BigDL-PR-Dllib-Validation/579/ pass

**Comment by jenniew** [comment]
@glorysdj should we put all jackson dependency version definition in parent pom, and only inference it in children pom? Or we specify all jackson dependency version individually in children pom?

**Comment by Le-Zheng** [comment]
Agreed with putting the Jackson dependency version definition in parent pom.

**Review by cyita — APPROVED** [review]

**Comment by Le-Zheng** [comment]
Jenkins pass: http://10.112.231.51:18888/job/BigDL-PR-Dllib-Validation/581/  http://10.112.231.51:18888/job/BigDL-Friesian-PR-Validation/196/

**Pull request merged**
