### PR TITLE
modify TextClassifier.scala

### PR DESCRIPTION
**Pull request by lival**
## What changes were proposed in this pull request?
Persist API in Spark are widely used can help us to improve performance.  The variables _frequencies_ at TextClassifier.scala:131,  _dataRdd_  at TextClassifier.scala:128, _sampleRDD_ at TextClassifier.scala:210 are used many times.  We should call persist to accelerate calculation.

### CODE REVIEW

**Comment by jason-dai** [comment]
@lival thanks for the PR.

@wzhongyuan please help with the testing.

**Comment by wzhongyuan** [comment]
Jenkins passed http://mlt-bddl01.sh.intel.com:8080/job/BigDL-PRVN-lite/1116/

**Comment by lival** [comment]
> Jenkins passed http://mlt-bddl01.sh.intel.com:8080/job/BigDL-PRVN-lite/1116/
@jason-dai  Thanks for your reply.
@wzhongyuan  Sorry, the link you gave could not be opened. Maybe it is an intranet that prevents me from accessing it? This problem will not affect the function. Fixing this problem helps us improve the execution efficiency.

**Comment by wzhongyuan** [comment]
@lival  yes, it's for internal use only, LGTM and I am merging it for you

**Pull request merged**
