### PR TITLE
Fix Java based model saving issue with size > 2GB

### PR DESCRIPTION
**Pull request by wzhongyuan**
## What changes were proposed in this pull request?
Fix Java based model saving issue with size > 2GB

## How was this patch tested?
Local test

## Related links or issues (optional)
fixed https://github.com/intel-analytics/BigDL/issues/1645

### CODE REVIEW

**Comment by wzhongyuan** [comment]
@qiuxin2012  Please help review, tested locally with big-sized model

**Comment by wzhongyuan** [comment]
PR validation passed
http://172.168.2.101:8080/job/BigDL-PR-V/198/

**Comment by qiuxin2012** [comment]
Please add a unit test for save&load a big model like `Linear(262144, 1024)`

**Comment by qiuxin2012** [comment]
LGTM

**Comment by wzhongyuan** [comment]
@qiuxin2012  Thanks, will merge it once Integration test passed,

**Comment by wzhongyuan** [comment]
PR passed http://172.168.2.101:8080/job/BigDL-PR-V/298/

**Pull request merged**
