### PR TITLE
remove init_method from python constructor to be compatible with scala api

### LINKED ISSUE #1056: Parameters differ between python and scala API in SpatialConvolution and SpatialFullConvolution
Below issue exists for SpatialConvolution and SpatialFullConvolution. 

- initGradWeight, initGradBias does not exist in python API. 
- initBias, initWeight are seperated but python API uses only init_method. 
- wRegularizer, bRegularizer does not exist in python API

```scala
val m = SpatialConvolution[Double](nInputPlane,nOutputPlane,kernelW,kernelH,strideW,strideH,padW,padH,nGroup,propagateBack,wRegularizer,bRegularizer,initWeight, initBias, initGradWeight, initGradBias) 
```

```python
m = SpatialConvolution(n_input_plane,n_output_plane,kernel_w,kernel_h,stride_w=1,stride_h=1,pad_w=0,pad_h=0,n_group=1,propagate_back=True,init_method="default")
```

### PR DESCRIPTION
**Pull request by yangw1234**
## What changes were proposed in this pull request?

remove init_method from python constructor to be compatible with scala api

## How was this patch tested?

existing tests

## Related links or issues (optional)
fixed #1056 #1029

### CODE REVIEW

**Comment by yangw1234** [comment]
pr validation pass

**Comment by yiheng** [comment]
LGTM.

**Comment by yangw1234** [comment]
pr validation pass

**Comment by yangw1234** [comment]
@yiheng I have made some other modifications, could you look at it again?

**Comment by yiheng** [comment]
LGTM

**Pull request merged**
