### PR TITLE
[branch-0.1]fix data may distribute unevenly in vgg example

### PR DESCRIPTION
**Pull request by qiuxin2012**
## What changes were proposed in this pull request?

fix data may distribute unevenly in vgg example when the cores and executors is bigger than 20 * 64.

## How was this patch tested?

unit tests, manual tests

### CODE REVIEW

**Comment by jason-dai** [comment]
Please test the examples on several large clusters too

**Comment by qiuxin2012** [comment]
@jason-dai Just passed testing VGG and Lenet examples on a 20cores*64nodes cluster with a 5120 batchSize.

**Comment by jason-dai** [comment]
Can you test other cluster configures - larger and/or smaller sizes?

**Comment by qiuxin2012** [comment]
@jason-dai Also works for 28core*64node, 10core*5node.
1core*1node, 4code*1node will cause another error: 
`Exception in thread "main" org.apache.spark.SparkException: Job aborted due to stage failure: Serialized task 0:0 was 155763217 bytes, which exceeds max allowed: spark.rpc.message.maxSize (134217728 bytes). Consider increasing spark.rpc.message.maxSize or using broadcast variables for large values.`
adding an spark conf spark.rpc.message.maxSize=200 could solve this exception. (Current branch-0.1 also have this problem)

**Comment by jason-dai** [comment]
We may need to add this config to the examples? @yiheng

**Comment by yiheng** [comment]
agree to add the config to the example.

**Comment by jason-dai** [comment]
How about ResNet? Other examples using Cifar-10 data?

**Comment by qiuxin2012** [comment]
@jason-dai Yeah, Resnet also need this configuration. After checking all usages of the `array()`, I find lenet(mnist) rnn(tinyshakespeare) autoencoder(mnist) don't need this configuration.

**Pull request merged**
